### ISSUE TITLE
The documentation doesn't match what's in a JAR file.

### ISSUE THREAD

**Issue by yampolskiy** [awslabs/amazon-kinesis-client#1]
For example where is this package at? com.amazonaws.services.kinesis.model

**Comment by brendan-p-lynch** [comment]
Here is an example of the javadoc for the most recent release of KCL v1.x. https://javadoc.io/static/com.amazonaws/amazon-kinesis-client/1.15.1/index.html?com/amazonaws/services/kinesis/clientlibrary/lib/worker/KinesisClientLibConfiguration.html
