### ISSUE TITLE
Providing different credentials for dynamodb / cloudwatch than kinesis stream

### ISSUE THREAD

**Issue by shakdoesgithub** [awslabs/amazon-kinesis-client#101]
We are consuming a kinesis stream that sits in another account and we are using assume role to consume that stream using the KCL multilang daemon (using c# for our app).  What we are trying to figure out is how to provide credentials so that the multilang daemon will use those credentials to use dynamo db and cloudwatch in our account and not in the cross account where the kinesis stream lives.

**Comment by pfifer** [comment]
I don't believe that is currently possible with the MultiLang Daemon.  Bringing all of the Kinesis client libraries that depend on the MultiLang daemon up to date is on our backlog, but I don't currently have a date for that.  

Others: Please comment, or add an reaction so we can prioritize this change.

**Comment by pfifer** [comment]
Support for different credentials for the various services was added in PR #111.

Feel free to reopen if you have any additional questions.
