### ISSUE TITLE
backpressure

### ISSUE THREAD

**Issue by simao** [awslabs/amazon-kinesis-client#107]
Hello,

Is there a way to control backpressure? If `processRecords` keeps getting called, an application can get in a situation where it can't process any more records and KCL should halt getRecord from kinesis, otherwise some messages need to be dropped.

The problem is, if the downstream app drops some messages and then receives some new messages, the app can get into a situation where it checkpoints new messages even though the dropped messages were not checkpointed.

**Comment by pfifer** [comment]
While a call to IRecordProcessor#processRecords is outstanding no new record will be retrieved.  It sounds like the downstream call to the app should be synchronous until it's accepted.  This will prevent processRecords from returning and additional messages being retrieved.

**Comment by simao** [comment]
I see what you mean but in our app is completely async, so we can't guarantee the call to processRecords will be sequential, so have some way to pause KCL until we can process more records would be a better way to control backpressure.

**Comment by pfifer** [comment]
I'm not sure what async method you're using, but most would have the concept of futures.  It should be possible to submit a set of tasks up to some number, and then wait on those future before returning from the processRecords call.  

If your async strategy is fire than forget, it's somewhat harder.  In those cases I would recommend figuring out an acceptable transactions per second rate, and use some throttling mechanism to ensure that you stay under that rate.  Token bucket is a common approach for this.

**Comment by pfifer** [comment]
Closing this for now, feel free to reopen if you have any further questions.
