### ISSUE TITLE
For multistream StreamIdentifier, why does it need to include the stream creation epoch time

### ISSUE THREAD

**Issue by litaobowl** [awslabs/amazon-kinesis-client#1093]
IMO, the lease key should not include the stream creation epoch time.

**Comment by litaobowl** [comment]
Is the stream creation time the time when you create the stream, or the time you create the StreamIdentifier object

**Comment by stair-aws** [comment]
> the structure of the leaseKey looks like this: `account-id:StreamName:streamCreationTimestamp:ShardId`

ref: https://docs.aws.amazon.com/streams/latest/dev/shared-throughput-kcl-consumers.html#shared-throughput-kcl-consumers-leasetable

The embedded epoch is the stream creation time, not a time specific to the `StreamIdentifier` object.

---

> [litaobowl@] IMO, the lease key should not include the stream creation epoch time.

FMI: why? What issue have you encountered, or use case you are attempting to solve?
