### ISSUE TITLE
How to skip the shard reading position to LATEST?

### ISSUE THREAD

**Issue by lune-sta** [awslabs/amazon-kinesis-client#1095]
I am developing a real-time application using KCL 2.4.8.
I want to skip the reading position to the `LATEST` when the Record's Millis Behind Latest becomes large.
`InitialPositionInStream.LATEST` was not effective if the lease was already allocated.

**Comment by wbarros** [comment]
The dynamodb save the checkpoint, the LATEST lose the effect when checkpoint saved. To run at LATEST, cleanup the dynamodb table.

**Comment by wbarros** [comment]
> I am developing a real-time application using KCL 2.4.8. I want to skip the reading position to the `LATEST` when the Record's Millis Behind Latest becomes large. `InitialPositionInStream.LATEST` was not effective if the lease was already allocated.


The dynamodb save the checkpoint, the LATEST lose the effect when checkpoint saved. To run at LATEST, cleanup the dynamodb table.
