### ISSUE TITLE
Sequence numbers monotonically increasing?

### ISSUE THREAD

**Issue by david-mcneil** [awslabs/amazon-kinesis-client#112]
When reading records in order are the Record.getSequenceNumber() values guaranteed to be monotonically increasing for a given partition key even across shard splits/merges?

I think another way of asking this question is whether the shardId (which I presume increases after splits/merges) is encoded as part of the record sequence number either by Kinesis or by the KCL?

Thanks.
-David

**Comment by pfifer** [comment]
For a given partition key, which maps to a shard at a given point in time, the sequence number should always be increasing.  This should hold true as shards are split, and merged as well.

**Comment by david-mcneil** [comment]
Thank you.

**Comment by pfifer** [comment]
Closing this, please reopen if you have more questions.

**Comment by thiagoh** [comment]
Are Sequence Numbers unique per partition key? Is is possible that two separate clients running on separate threads write a record to the same partition key and end up having the same seq. number?
