### ISSUE TITLE
DynamoDB Streams lag monitoring

### ISSUE THREAD

**Issue by ivanarkhipov** [awslabs/amazon-kinesis-client#113]
Hello!
We're using DynamoDB Streams + Kinesis Client Library (KCL).
How can we measure latency between event was created in a stream and it was processed on KCL side?

As I know, KCL's `MillisBehindLatest` metric is specific to Kinesis Streams. 
`approximateCreationDateTime` record attribute has a minute-level approximation, which is not acceptable for monitoring in sub-second latency systems.
Could you please help with some useful metrics for monitoringDynamoDB Streams latency?

Thank you!

Ivan

**Comment by pfifer** [comment]
Thanks for the input.  I've sent a request internally to the DynamoDB team to investigate this.

**Comment by pfifer** [comment]
This feature is currently on their road map, but don't currently have an ETA.

I'm going to close this in favor of the [issue in the DynamoDB Streams Kinesis Adaptor](https://github.com/awslabs/dynamodb-streams-kinesis-adapter/issues/5)

**Comment by ivanarkhipov** [comment]
Thank you.
