### ISSUE TITLE
Send CloudWatch metrics to a single namespace

### ISSUE THREAD

**Issue by xose** [awslabs/amazon-kinesis-client#115]
The Kinesis Client should store its metrics on a single namespace, with the application name stored as a dimension on the metrics.

* Running many Kinesis Clients (especially if some of them are temporary, or may change names) pollutes the CloudWatch interface. There is no way to remove a metric/namespace, so any new application name will linger around for *15 months* on the Namespaces list.
* All other AWS CloudWatch metrics work like this, with the "source" of the metric stored as a dimension.
* The Kinesis Producer also uses a single namespace, so this would be more consistent.
* It would be easier to find and compare metrics from different Clients on the CloudWatch interface.
* 3rd party monitoring tools with CloudWatch integration (ie. Prometheus, Grafana, ...) would be able to discover the Client application names.

**Comment by smartnut007** [comment]
👍  Created a ticket requesting changes with a broader scope here https://github.com/awslabs/amazon-kinesis-client/issues/117

**Comment by pfifer** [comment]
I'm going to close this in favor of the #117
