### ISSUE TITLE
Clarification about DynamoDB initial configuration for KCL with consumer application

### ISSUE THREAD

**Issue by cbugneac-nex** [awslabs/amazon-kinesis-client#1182]
Hi,

The AWS docs https://docs.aws.amazon.com/streams/latest/dev/shared-throughput-kcl-consumers.html doesn't mention how DynamoDB should be configured for KCL.
They rely on fact of granting DynamoDB permissions to KCL which is not ideal.

We don't want to allow KCL CreateTable IAM permission to create resource dynamically and prefer to provision DynamoDB table via IaC (Terraform).
Please could someone shed some light on what we need to specify as primary key (partition key), any attributes requires, etc.

Thanks

**Comment by stair-aws** [comment]
Salut! At present, the best source of truth is the code itself. You can discern the PK in `DynamoDBLeaseSerializer`: https://github.com/awslabs/amazon-kinesis-client/blob/8d1ee6b5e16ecb53c393b24439b8fc566fa29de0/amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/dynamodb/DynamoDBLeaseSerializer.java#L311-L322

Through KCL configuration, additional attributes may be set such as the billing mode and DDB tags: https://github.com/awslabs/amazon-kinesis-client/blob/8d1ee6b5e16ecb53c393b24439b8fc566fa29de0/amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/dynamodb/DynamoDBLeaseRefresher.java#L806-L814

Hopefully this will unblock you.
