### ISSUE TITLE
Feature Request: Stream name in aws kcl consumer when MultiStreamTracker is used

### ISSUE THREAD

**Issue by gurudatta-carbon** [awslabs/amazon-kinesis-client#1199]
- When using [MultiStreamTracker](https://github.com/awslabs/amazon-kinesis-client/blob/a1731dc49b2d76b8dd33781d5cabc5264b7079f9/amazon-kinesis-client/src/main/java/software/amazon/kinesis/processor/MultiStreamTracker.java) in aws kcl 2.x, how to find out from which stream the message is from. In [KinesisClientRecord](https://github.com/awslabs/amazon-kinesis-client/blob/a1731dc49b2d76b8dd33781d5cabc5264b7079f9/amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/KinesisClientRecord.java), there isn't a attribute for that.
- If multiple streams have different payload structures, it would be nice to know from which stream is the record from and helpful in deserializing it.
- Also not available in [ShardRecordProcessor](https://github.com/awslabs/amazon-kinesis-client/blob/a1731dc49b2d76b8dd33781d5cabc5264b7079f9/amazon-kinesis-client/src/main/java/software/amazon/kinesis/processor/ShardRecordProcessor.java#L46) as well
- Version of kcl = 2.5.2

**Comment by gurudatta-carbon** [comment]
@stair-aws 
any idea on when this can be picked up ?

are there any workarounds meanwhile for this ?

**Comment by gurudatta-carbon** [comment]
was able to achieve this via implementing shard record processor factory

```
private class KinesisShardProcessorFactory(private val shardRecordProcessors: List<StreamConsumer<*>>) :
    ShardRecordProcessorFactory {

    override fun shardRecordProcessor(): ShardRecordProcessor {
        throw UnsupportedOperationException("")
    }
    override fun shardRecordProcessor(streamIdentifier: StreamIdentifier): ShardRecordProcessor {
        return shardRecordProcessors.first { it.name == streamIdentifier.streamName() }
    }
}
```

**Comment by zeynepsu** [comment]
Thank you for your suggestion, we will add more clarification into our docs.

**Comment by kschwarz1116** [comment]
I've come across this recently too. It doesn't seem like `fun shardRecordProcessor()` is used if `fun shardRecordProcessor(streamIdentifier: StreamIdentifier)` is defined. If that's actually the case, it would be great to update the API here so that I don't have to worry about implementing an unused function.

If it's not, then I would like to know how the KCL decides to use each function.
