### ISSUE TITLE
ShardInfo class not public

### ISSUE THREAD

**Issue by dlsteuer** [awslabs/amazon-kinesis-client#120]
Just checking to see if this is just an oversight, but the ShardInfo class is non-public and so it's not possible to provide a custom ShardPrioritization implementation that compiles because of this.

**Comment by pfifer** [comment]
Looking at it, I think it's an oversight.  The existing strategies just happen to be in the same package so they don't have that issue.

I'll look at making the class public for a future release.  For the short term you could place your strategy in the same package: com.amazonaws.services.kinesis.clientlibrary.lib.worker

**Comment by pfifer** [comment]
This is now fixed in Release 1.7.3.

Feel free to reopen if you have any additional questions.
