### ISSUE TITLE
Problem in ts-tsbgservice-kinesis-incoming-emea-prod

### ISSUE THREAD

**Issue by SergioFernandezBMW** [awslabs/amazon-kinesis-client#1201]
Hello we are having some issues with ts-tsbgservice-kinesis-incoming-emea-prod

![image](https://github.com/awslabs/amazon-kinesis-client/assets/143504270/bea018c0-a842-44a2-afe2-d3811ee6b489)
![image](https://github.com/awslabs/amazon-kinesis-client/assets/143504270/392cc960-aaed-463d-aabc-7c7d862fb3c8)
![image](https://github.com/awslabs/amazon-kinesis-client/assets/143504270/8d581216-e890-4c4c-a9ce-be0cc2b6226e)

In dynatrace we also see that the top contributor of the problem is:

![image](https://github.com/awslabs/amazon-kinesis-client/assets/143504270/3064bd44-af57-4183-943f-7bda78f0fd17)

please if you can check if something is happening in the kinesis stream would be nice.

Thank you so much,
KR,

Contact: sergio.fernandezbarquilla@partner.bmwgroup.com & AmadorAntonio.OrtizCarvajal@partner.bmwgroup.com

**Comment by stair-aws** [comment]
@SergioFernandezBMW Salut! Questions:
1. Which version of KCL?
    * If not at the latest for the branch (i.e., 1.15.0, 2.52.2), does upgrading lessen or eliminate the incident?
1. Is this a standalone KCL app, or is KCL embedded in a call chain (e.g., Lambda)?
3. From CloudWatch logs, there's a suggested weekly pattern (usually Wed +/- a day). Any insight into how your traffic might be different on these days, if at all? (e.g., 10x higher volume)
4. Would you kindly provide logs for an affected shard prior-to the `Unexpected exception`? Also, a stacktrace would help us troubleshoot.

**Comment by stair-aws** [comment]
No response; closing.
