### ISSUE TITLE
Port of multilang to .net Core

### ISSUE THREAD

**Issue by fouimette** [awslabs/amazon-kinesis-client#121]
Looking at the code here, I did not see any reason why we are not able to port this to .net core.  Is there anything that I am missing that would prevent this?

Doing so would dramatically reduce docker image sizes by not having to include Java.  
Java => 600mb (or so)
.net Core => 250mb (or so)  <----- way smaller

Your thoughts?

**Comment by pfifer** [comment]
Thanks for reporting this, but at this time we won't be doing a port of the Kinesis Client Library to .NET core.  We are looking into other options that would allow us to provide a slimmer executable size.
