### ISSUE TITLE
Please update your schema-registry-serde library in order to solve CVE issue

### ISSUE THREAD

**Issue by mptak-tbscg** [awslabs/amazon-kinesis-client#1210]
There is a CVE problem with the 'com.charleskorn.kaml' library, which is one of the transitive dependencies of 'software.amazon.kinesis:amazon-kinesis-client'.

![kaml loc](https://github.com/awslabs/amazon-kinesis-client/assets/141401509/43753e16-eeac-45ef-97bf-fbf5701ed1ba)

After conducting research, I have determined that this issue is resolved in the newer version of 'software.amazon.glue:schema-registry-serde' (which is a direct dependency of the Kinesis library). Therefore, I would recommend updating this dependency from version 1.1.14 to 1.1.16.

**Comment by brendan-p-lynch** [comment]
Resolved in latest commit: https://github.com/awslabs/amazon-kinesis-client/commit/cf5e1e4c7ff64a9e1929d2999e4b48d7c422fb7b
