### ISSUE TITLE
GetMessageTask.handleLineResult() eats exceptions

### ISSUE THREAD

**Issue by seanpd** [awslabs/amazon-kinesis-client#122]
GetMessageTask.java:70
...
        } catch (IOException e) {
            LOG.info("Skipping unexpected line on STDOUT for shard " + getShardId() + ": " + line);

Note that 'e' is ignored, which is bad.  Here is a case I ran into that caused misleading
logging:

INFO: Skipping unexpected line on STDOUT for shard shardId-000000000000: {"action":"checkpoint","checkpoint":null,"error":null}

However the actual root cause is:

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "checkpoint" (class com.amazonaws.services.kinesis.multilang.messages.CheckpointMessage), not marked as ignorable (3 known properties: "error", "sequenceNumber", "subSequenceNumber"])
 at [Source: {"action":"checkpoint","checkpoint":null,"error":null}; line: 1, column: 41] (through reference chain: com.amazonaws.services.kinesis.multilang.messages.CheckpointMessage["checkpoint"])

**Comment by pfifer** [comment]
Thanks for reporting this.  I will investigate making the message more informative.

Which Multilang Daemon client are you using?

**Comment by seanpd** [comment]
I'm working with the .NET client
https://github.com/awslabs/amazon-kinesis-client-net

It's 1.5 years old and may be out of sync.  I encountered the multiline issue while debugging this.

**Comment by pfifer** [comment]
It's a small fix to upgrade to newer versions of the KCL, and I'm planning to make the compatibility changes to the .NET client soon.

**Comment by seanpd** [comment]
Thanks!  Do you have a rough time frame for fixing the .NET client?
I was considering not using it because it didn't look well supported.

**Comment by seanpd** [comment]
On the .NET client:
ClientLibrary.cs:430
I tried changing 
        [DataMember(Name = "checkpoint")]
to
        [DataMember(Name = "sequenceNumber")]

That alone seems to make it happy; checkpoints were working as expected.

**Comment by pfifer** [comment]
That's pretty much the entire required change.  Adding support for the newer features is a longer term issue.  I will make the same change, and release it in the near future.

**Comment by pfifer** [comment]
The .NET Client has been updated to use Kinesis Client Library 1.7.2.
