### ISSUE TITLE
amazon-kinesis-client-pom using old awssdk.version

### ISSUE THREAD

**Issue by subash89** [awslabs/amazon-kinesis-client#1231]
A parent of software.amazon.kinesis:amazon-kinesis-client  points to old aws sdk version in (amazon-kinesis-client-pom)
The property if 
`    <awssdk.version>2.20.43</awssdk.version>
`
This lead packing old cloudwatch like jars into kinesis client.

**Comment by pawelryznar** [comment]
Yep, version bump would be useful. Currently it is blocking upgrade of AWS SDK in the applications to v2.22.* because there were some backward incompatible changes in the SDK, and using new SDK with kinesis client 2.5.4 causes errors:

> software/amazon/awssdk/services/cloudwatch/DefaultCloudWatchBaseClientBuilder.java
> should not use non existing class software.amazon.awssdk.protocols.query.interceptor.QueryParametersToBodyInterceptor

Why is Dependabot not picking that up?

**Comment by chrisxaustin** [comment]
Version 2.20.43 is very outdated since it was released last April - can this be updated soon?
