### ISSUE TITLE
Consolidate metrics to a common name space, like /aws/kinesis-client

### ISSUE THREAD

**Issue by nlm4145** [awslabs/amazon-kinesis-client#1246]

**Comment by brendan-p-lynch** [comment]
Thank you for reaching out about this request. Can you help describe the benefit for this? Are you looking to prepend the current metric location with aws/kinesis-client, and then have the application name after that?

As it is currently designed we would need some kind of distinction between each application in the metrics, as not doing so could lead to two different applications overwriting each other, so we want to have a different namespace for each application.

Please further reach out with what the ask here would be.

**Comment by brendan-p-lynch** [comment]
Closing as there is no communication on the ask. Feel free to reopen if there is more clarity in the request.
