### ISSUE TITLE
Version 1.7.3 Not Available in Maven Central

### ISSUE THREAD

**Issue by az3** [awslabs/amazon-kinesis-client#132]
Hello,

amazon-kinesis-client-1.7.3 is not available in the Maven Central, can you please check?
https://repo.maven.apache.org/maven2/com/amazonaws/amazon-kinesis-client/maven-metadata.xml

Thanks.

**Comment by pfifer** [comment]
I just completed the release process, it should show up in Maven soon.

Sorry about the delay.
