### ISSUE TITLE
2.6.0 release not available on Maven Central

### ISSUE THREAD

**Issue by cap10morgan** [awslabs/amazon-kinesis-client#1328]
It looks like version 2.5.8 is still the latest available version on Maven Central: https://mvnrepository.com/artifact/software.amazon.kinesis/amazon-kinesis-client

Can you deploy release 2.6.0 to Maven Central?

**Comment by michaelzelaia** [comment]
Looks like version 2.6.0 is available now.

**Comment by cap10morgan** [comment]
Looks good now, thanks!
