### ISSUE TITLE
THROUGHOUT_PUT_KBPS spelling error

### ISSUE THREAD

**Issue by jhmartin** [awslabs/amazon-kinesis-client#1397]
https://github.com/awslabs/amazon-kinesis-client/blob/f7e909c979a5dd1cbd68ed47be26fd1056721acd/amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/dynamodb/DynamoDBLeaseSerializer.java#L57 misspells 'throughput' in the constant name.

**Comment by akidambisrinivasan** [comment]
Fix will be part of next release
