### ISSUE TITLE
Logging to logstash

### ISSUE THREAD

**Issue by shakdoesgithub** [awslabs/amazon-kinesis-client#144]
Is there a way to specify to send logs to an endpoint such as logstash?
I'm using the multilang daemon v1.7.0 with C# client

**Comment by joelittlejohn** [comment]
Rather than have every library integrate with every log aggregation backend directly, it's much more common to run a daemon that watches your log files and sends new log items on to logstash.

**Comment by danieljamesscott** [comment]
You should be able to get your logging framework to output directly to logstash

https://github.com/logstash/logstash-logback-encoder

**Comment by prayagupd** [comment]
Totally agree with @joelittlejohn. 

- I use `jsonevent-layout` jar to convert logs to JSON format, it basically writes kinesis logs/ or app logs in JSON format.

```xml
<dependency>
    <groupId>net.logstash.log4j</groupId>
    <artifactId>jsonevent-layout</artifactId>
    <version>1.7</version>
</dependency>
```

- then use filebeat outside the application to send those logs to logstash (only if mutation on log-events is needed) or directly to elasticsearch.

- configure kibana on that elasticsearch for visualisation.
