### ISSUE TITLE
is there a way to check whether a Worker is ready for business?

### ISSUE THREAD

**Issue by elisehuard** [awslabs/amazon-kinesis-client#147]
For our tests, we'd like to check whether a worker is ready to start consuming before we start our tests producing events - programatically.  We can't see a way in the code (no attributes are being set) - did we miss something, is there a way to do this?
If not, is there a plan to do this, or if not, would you be open to a pull request?

**Comment by mantree** [comment]
Created a PR that adds a flag for this:

https://github.com/awslabs/amazon-kinesis-client/pull/148
