### ISSUE TITLE
Allow tagging of the dynamodb table created by KCL

### ISSUE THREAD

**Issue by RyanFrench** [awslabs/amazon-kinesis-client#154]
For billing purposes, we would like to be able to tag the dynamodb table that is created by KCL. Something like a key/value map passed in via the properties file, or written explicitly in code. Allowing multiple tags to be added would be ideal.

**Comment by pfifer** [comment]
Thank you for your suggestion. We would like to add this feature, and will prioritize this with other customer requests.

If anyone else is interested in the feature please comment, or add a reaction.

**Comment by jqr** [comment]
Not a huge deal, but this would be nice!

**Comment by SRELETI** [comment]
+1

**Comment by muhufuk** [comment]
+1

**Comment by renier-rhode** [comment]
+1

**Comment by stroebs** [comment]
+1. Tagging is imperative to business resource-allocation.

**Comment by arthur78** [comment]
+1

**Comment by amithgeorge** [comment]
Any updates on this?

**Comment by mmritesh** [comment]
+1

**Comment by s4r4r** [comment]
+1

**Comment by max79137913** [comment]
+1

**Comment by joshimadhavi** [comment]
Any updates on this? Is this released in any new version?

**Comment by mmritesh** [comment]
This would be really helpful.
For now I need to come up with some workaround to tag the table, please suggest if anyone has already added some workaround?

**Comment by karinpb** [comment]
Still not implemented?

**Comment by abargnesi** [comment]
It looks like you can use a TableCreatorCallback to apply tags after the table is created the first time:

https://github.com/awslabs/amazon-kinesis-client/blob/master/amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/dynamodb/TableCreatorCallback.java

**Comment by adrian-baker** [comment]
Besides being extra work, using a callback prevents the use of a tag policy that enforces dynamodb tables can't be created without tags

**Comment by towerbe** [comment]
5 years and still no fix?  Come on AWS.  You're better than that.  These resources really need to be tagged at creation time natively, not via some work around.

**Comment by EdHoweNexidia** [comment]
+1

**Comment by stair-aws** [comment]
@RyanFrench Thanks for taking ownership and providing a solution! This feature will be available in the next release of KCL 2.x (i.e., the version _after_ [2.4.8](https://github.com/awslabs/amazon-kinesis-client/blob/master/CHANGELOG.md) which just released).
