### ISSUE TITLE
MultiLangRecordProcessor does not implement IShutdownNotificationAware

### ISSUE THREAD

**Issue by ewalker11** [awslabs/amazon-kinesis-client#159]
As far as I can tell, the `MultiLangRecordProcessor` does not implement `IShutdownNotificationAware`. As such, non-java KCL applications are unable to make use of the graceful shutdown semantics introduced here: https://github.com/awslabs/amazon-kinesis-client/pull/109. It would be really amazing if they could!

**Comment by pfifer** [comment]
This is in progress in #174

**Comment by pfifer** [comment]
Now completed and released as part of v 1.7.6
