### ISSUE TITLE
KCL 1.6.4 advertises JDK 7 / 51.0 compatibility but bytecode is actually 52.0 (JDK 8)

### ISSUE THREAD

**Issue by amcp** [awslabs/amazon-kinesis-client#162]
Looking at the [1.6.4 tag of KCL pom.xml](https://github.com/awslabs/amazon-kinesis-client/blob/v1.6.4/pom.xml#L86) shows that source needs to be compatible with 1.7 and the compilation target is also 1.7. However, the bytecode in the published artifact is JDK8.

```bash
$ mkdir temp && cd temp
$ wget http://central.maven.org/maven2/com/amazonaws/amazon-kinesis-client/1.6.4/amazon-kinesis-client-1.6.4.jar
$ jar xf amazon-kinesis-client-1.6.4.jar
$ cd com/amazonaws/services/kinesis/clientlibrary/lib/worker
$ file KinesisClientLibLeaseCoordinator.class
KinesisClientLibLeaseCoordinator.class: compiled Java class data, version 52.0 (Java 1.8)
```

**Comment by amcp** [comment]
However, [1.7.5 advertises JDK 7 compatibility](https://github.com/awslabs/amazon-kinesis-client/blob/master/pom.xml#L134) but the bytecode is for JDK 7 this time.

```bash
$ mkdir temp && cd temp
$ wget http://central.maven.org/maven2/com/amazonaws/amazon-kinesis-client/1.7.5/amazon-kinesis-client-1.7.5.jar
$ jar xf amazon-kinesis-client-1.7.5.jar
$ cd com/amazonaws/services/kinesis/clientlibrary/lib/worker
$ file KinesisClientLibLeaseCoordinator.class
KinesisClientLibLeaseCoordinator.class: compiled Java class data, version 51.0 (Java 1.7)
```

**Comment by pfifer** [comment]
The correct configuration was missing for previous versions of the KCL, so the output was whatever JVM was building the jar file.  

I would need to know how important replacing the old version would be especially with the DynamoDB adapter now support KCL 1.7.x.

If it's important please feel free to re-open this.

Thanks
