### ISSUE TITLE
is Amazon KCL 1.7.5 compatible with elasticSearch 5.1.1?

### ISSUE THREAD

**Issue by ysyzygy** [awslabs/amazon-kinesis-client#165]
is Amazon KCL 1.7.5 compatible with elasticSearch 5.1.1?

Thanks!

**Comment by pfifer** [comment]
The Kinesis Client Library has nothing that would cause problems for Elasticsearch.  

It looks like you also posted on https://github.com/awslabs/amazon-kinesis-connectors/issues/82.  I'm going to close this in favor of that issue.
