### ISSUE TITLE
If the KCL is restarted, will it start process from the previous checkpoint?

### ISSUE THREAD

**Issue by knexp** [awslabs/amazon-kinesis-client#17]
Fail over Scenarios like "KCL Application is restarted" or  "AWS Instance reccovery", will it start process from the checkpoint?

http://docs.aws.amazon.com/kinesis/latest/dev/kinesis-record-processor-failover-recovery.html

**Comment by knorwood** [comment]
Yes. Whenever a new KCL Worker starts up it gets some number of shards assigned to it. It then begins processing those shards from the most recent checkpoint. The reason for a new worker starting up could be because of a failover like you described.

**Comment by knexp** [comment]
Thanks @knorwood . I'm clear.

**Comment by abhinavkk** [comment]
@knorwood Say for example I was processing some DynamoDB Stream records through a lambda function that triggers in every N minutes. Will the next trigger start processing the records from the last processed record in the previous trigger?

**Comment by pfifer** [comment]
Lambda uses a different processing, and checkpointing model than the KCL. I would recommend asking the question on the [official forums for Lambda](https://forums.aws.amazon.com/forum.jspa?forumID=186)

**Comment by baileytcj** [comment]
@knorwood @pfifer My KCL application doesn't process from the last checkpoint and just sits idle after restarting. 
Initially, I have a producer writing to one stream one shard with a KCL reading from it. For testing failure scenario purpose, I brought down the KCL for 10 mins, while the producer kept still running. I stopped the producer before bringing the KCL back up to see if it would process the records it missed. But it just sat idle after coming back up. 

How could I tell the KCL to use the Dynamo table that it created before and not just wait for the latest record to come in?

**Comment by demuetz** [comment]
@baileytcj , did you configure your `KinesisClientLibConfiguration` to use TRIM_HORIZON instead of LATEST? I.e., did you use `withInitialPositionInStream(InitialPositionInStream.TRIM_HORIZON)` on it?

**Comment by baileytcj** [comment]
Closing this. I was running the StockProcessor example and didn't realize it was checkpointing every minute until I looked further into it. Once I turned on logging, everything made more sense.
