### ISSUE TITLE
does MultiLangDaemon support `AWSCredentialsProvider = ProfileCredentialsProvider` ?

### ISSUE THREAD

**Issue by AnatoliiAPFM** [awslabs/amazon-kinesis-client#178]
Hi,
can someone advise if MultiLangDaemon support `AWSCredentialsProvider = ProfileCredentialsProvider` in kcl.properties?

and if so then is there a property that can specify the name of credentials profile?

thanks in advance!
-Anatolii

**Comment by pfifer** [comment]
Yes it should, but you need to use the full package name for the class.  If you need to provide properties you will need to use a pipe (`|`) to separate them.

Here is a simple example: 
```
AWSCredentialsProvider = com.amazonaws.auth.profile.ProfileCredentialsProvider
```

If you need to provide a profile name:
```
AWSCredentialsProvider = com.amazonaws.auth.profile.ProfileCredentialsProvider|<profile name>
```

Please re-open if you need any more assistance.
