### ISSUE TITLE
No Tags?

### ISSUE THREAD

**Issue by aviflax** [awslabs/amazon-kinesis-client#19]
Since the repo has no tags, how am I supposed to know which revision represents a given release version, e.g. the current release is 1.21 but which revision is that? Is master always the current prod release or is master unstable? Help?

**Comment by knorwood** [comment]
Hi @aviflax,

Thanks for bringing this oversight to our attention. I've added some tags to identify which commits represent which version of the library. We attempt to keep the HEAD of master stable, but from now on we will also use tags to indicate version stability.

Thanks,
Kurt

**Comment by aviflax** [comment]
Great, thanks!
