### ISSUE TITLE
Checkpointing not works as expected

### ISSUE THREAD

**Issue by alparslanuysal** [awslabs/amazon-kinesis-client#192]
Hi team, I have only one stream and a consumer application which emits the records , transforms and writes to the InfluxDB.When I restart the consumer application, it restores the records from stream that are not checkpointed.However, there is a scenario that destination service may be unavailable for some reason.In that case, when consumer application gets an connection exception, it does not checkpoint the sequence number.I checked the DynamoDB table , it didn't update the sequence number.After I started the destination service(InfluxDB),  consumer application did not get records from where it left off, it got the latest sequence number.

**Comment by sahilpalvia** [comment]
Is your processRecords throwing an exception when InfluxDB is not available? If that is the case the KCL moves on the get the next set of records. Once the call is returned from the processRecords method KCL expects all the processing to have completed and moves on to get the next set of records. Exceptions in the processRecords method should be handled with the method. Checkout #10, it is related to exception handling within processRecords. Please feel free to reopen the issue, if that doesn't solve your issue.
