### ISSUE TITLE
withTimestampAtInitialPositionInStream not work

### ISSUE THREAD

**Issue by cwei-bgl** [awslabs/amazon-kinesis-client#196]
Hi,

I am having a sync process like this: 1. Kinesis checkpoint -> 2. full sync -> 3. Kinesis catch up sync. The catch-up sync is supposed to start from "1. Kinesis checkpoint". I tried the following two approaches without success.

Approach one:
1. Store current time -> 2. full sync(could take some hours) -> 3. Kinesis catch-up 
 by KinesisClientLibConfiguration.withTimestampAtInitialPositionInStream with stored time . But it is always starting from 24 hours ago. The dynamodb table for the worker is pre-existed. I just wonder in what condition it will ignore my TimestampAtInitialPositionInStream parameter? is it because there was a checkpoint in the dynamodb table?

Approach two:
1. Start Kinesis worker, read some records and checkpoint -> 2. full sync(could take some hours) -> 3. Kinesis catch up 
 by KinesisClientLibConfiguration.withInitialPositionInStream with InitialPositionInStream.TRIM_HORIZON. It does not start from the checkpoint but start from 24 hours ago. 

Is there anything wrong with my approaches?

**Comment by pfifer** [comment]
The KCL will only use the timestamp when no leases already exist.  It's very likely that leases exist in the lease table, so the KCL is using the sequence number stored there instead of the timestamp position.  If you want to trigger the KCL to start from the timestamp you would need to remove the existing leases.

**Comment by cwei-bgl** [comment]
@pfifer does leases only exist when there is an active consumer? Will the leases be removed once a consumer becomes inactive for some time? Because my second step full sync will take some time, I assume the leases will expire and be removed, and therefore timestamp will get applied?

**Comment by pfifer** [comment]
The KCL will always use the lease if it's present.  The only way to trigger the worker to use the initial position in stream is to remove the leases.  Removing the leases while the workers are running is difficult, and the usual case would be to stop the workers, remove the leases or lease table, and restart the workers.

**Comment by cwei-bgl** [comment]
@pfifer From your explanation, the approach two will work then? But why is it not working? Why is it starting from 24 hours ago instead of the checkpoint I made some hours ago? Is it because checkpoint cannot be reused by a different worker?

1. Start Kinesis worker, read some records and checkpoint -> 
2. full sync(could take some hours) -> 
3. Kinesis catch up by KinesisClientLibConfiguration.withInitialPositionInStream with InitialPositionInStream.TRIM_HORIZON. It does not start from the checkpoint but start from 24 hours ago.

Thanks, Cheng

**Comment by pfifer** [comment]
It should always start from the last checkpoint, not sure why it isn't.  
Can you let the application run for a bit, and make sure the sequence number value is changing?  In your record processor's initialization method can you also log the sequence number you're starting from?

**Comment by cwei-bgl** [comment]
@pfifer Thanks. I will have a try when next available and get back to you.

**Comment by sahilpalvia** [comment]
Closing issue, fell free to reopen if problem persists.
