### ISSUE TITLE
Plans to build a new version of KCL using aws-sdk-java-v2?

### ISSUE THREAD

**Issue by thesurlydev** [awslabs/amazon-kinesis-client#199]
I'm curious if there are plans to leverage aws-sdk-java-v2 to provide an updated version of KCL? If not, is this something that would be acceptable as a contribution?

**Comment by pfifer** [comment]
We do plan a transition of the KCL to the new version of the AWS SDK when it's released. It's possible we may start before release, but I don't currently have a schedule for the change.  We always welcome changes, but we may take the update to the new version of the SDK to make larger changes in the KCL.

**Comment by digitalsanctum** [comment]
Great to hear. Thanks for the reply.
