### ISSUE TITLE
KCL cannot process all leases when the it just reaches maxLeasesForWorker 

### ISSUE THREAD

**Issue by Jackyjjc** [awslabs/amazon-kinesis-client#202]
We are on 1.7.4 of the KCL library. Our Kinesis stream has 120 shards and our KCL runs on 3 EC2 nodes, each of them is configured to have maxLeasesForWorker=40. Theoretically 3 * 40 should be able to handle exactly 120 shards. However, what we see is that all of the workers kept emitting the following message:
```
Worker i-xxxxxxxxxxxxx target is 41 leases and maxLeasesForWorker is 40. Resetting target to 40, lease spillover is 1.  Note that some shards may not be processed if no other workers are able to pick them up.
```
This error messages happens on all 3 of the workers and it keeps happening and some of the shards are not being processed as a result.

**Comment by pfifer** [comment]
The message indicates that there are more than 120 leases in total.  The [LeaseTaker code](https://github.com/awslabs/amazon-kinesis-client/blob/51663f96c712da74daeeee2131953c8d8a515cc4/src/main/java/com/amazonaws/services/kinesis/leases/impl/LeaseTaker.java#L353) for reference.

I would not recommend to running this tight.  You want to have some additional capacity to ensure that host failures or other problems don't prevent processing of the inbound data.

**Comment by pfifer** [comment]
Feel free to reopen this if you have more questions.

**Comment by Jackyjjc** [comment]
Seems like the problem was due to Kinesis stream scaling. We scaled up the number of shards from 100 to 120. That results in having 122 entries in the KCL lease table for some reason. Thanks for the response

**Comment by Jackyjjc** [comment]
When does KCL delete the close shards from the lease table? I will check the code as well but you might know it on top of your head.

**Comment by pfifer** [comment]
Leases are deleted when the children of the leases are acquired for processing.  I would verify that your stream is 120 shards, just in case.
