### ISSUE TITLE
API changes review for Amazon Kinesis Client

### ISSUE THREAD

**Issue by lvc** [awslabs/amazon-kinesis-client#205]
The review of API changes for the Amazon Kinesis Client library since 1.0.0 version: https://abi-laboratory.pro/java/tracker/timeline/amazon-kinesis-client/

The report is updated three times a week. Hope it will be helpful for users and maintainers of the library.

The report is generated by https://github.com/lvc/japi-tracker and https://github.com/lvc/japi-compliance-checker tools.

Thank you.

![amazon-kinesis-client-1](https://user-images.githubusercontent.com/1517837/29457620-29985e0a-842c-11e7-9ca4-d35a3c7d857a.png)
![amazon-kinesis-client-2](https://user-images.githubusercontent.com/1517837/29457624-2d9a41f8-842c-11e7-910d-0d29e09d48bd.png)

**Comment by pfifer** [comment]
Thank you for this, but closing for now.
