### ISSUE TITLE
KinesisConnectorRecordProcessor: Shutting down record processor with shardId

### ISSUE THREAD

**Issue by gathole** [awslabs/amazon-kinesis-client#206]
I am running 3 Kinesis workers to consume DynamoDB streams from 3 different tables. But workers are not getting stream and in logs I can see below log which might be causing not getting stream

`
24 Aug 2017 04:37:19,719 [INFO]  (pool-6-thread-2) com.amazonaws.services.kinesis.connectors.KinesisConnectorRecordProcessor: Shutting down record processor with shardId: shardId-00000001503473258207-a947db72 with reason TERMINATE
`

How can I prevent shard being terminated and make sure stream is coming all the time?

**Comment by pfifer** [comment]
When a shard ends the record processor is asked to checkpoint one final time to indicate that it has completed processing on the shard.  The indication that the shard has ended is when the shutdown reason is TERMINATE.  See the [documentation for `IRecordProcessor#shutdown(...)`](https://github.com/awslabs/amazon-kinesis-client/blob/master/src/main/java/com/amazonaws/services/kinesis/clientlibrary/interfaces/v2/IRecordProcessor.java#L46-L58), also the [documentation on `ShutdownReason#TERMINATE`](https://github.com/awslabs/amazon-kinesis-client/blob/master/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/ShutdownReason.java#L38-L43).

**Comment by sahilpalvia** [comment]
Closing, feel free to reopen if issue persists.
