### ISSUE TITLE
Caused by: java.lang.NoSuchFieldError: com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.endpointPrefix 

### ISSUE THREAD

**Issue by praducg** [awslabs/amazon-kinesis-client#208]
I am trying to connect my andoid app to dynamo db for CRUD operation when I click on any button it throws, "Unforutunately app stopped working" from my android device with following log at backend[log cat]

Process: com.connect.dynamodb.connecttodynamodb, PID: 16283 java.lang.RuntimeException: An error occured while executing doInBackground() at android.os.AsyncTask$3.done(AsyncTask.java:300) at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355) at java.util.concurrent.FutureTask.setException(FutureTask.java:222) at java.util.concurrent.FutureTask.run(FutureTask.java:242) at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) at java.lang.Thread.run(Thread.java:841) Caused by: java.lang.NoSuchFieldError: com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.endpointPrefix at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.init(AmazonDynamoDBClient.java:460) at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.(AmazonDynamoDBClient.java:444) at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.(AmazonDynamoDBClient.java:392) at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.(AmazonDynamoDBClient.java:361)

I posted a question.Please go though for more clarity.
https://stackoverflow.com/questions/46042288/java-lang-nosuchfielderror-com-amazonaws-services-dynamodbv2-amazondynamodbclie

**Comment by pfifer** [comment]
This repository is for the Kinesis Client, and it looks like this is solely about the Amazon DynamoDB Client.  I would recommend opening a post on the [DynamoDB Forums](https://forums.aws.amazon.com/forum.jspa?forumID=131).
