### ISSUE TITLE
Better proxy support out of the box

### ISSUE THREAD

**Issue by rileymcdowell** [awslabs/amazon-kinesis-client#23]
The main issue is that the library doesn't use system proxy environment variables by default. On most linux systems, the environment variables http_proxy, https_proxy, and no_proxy are assumed to describe the correct proxies to use for http and https connections. This library does not use these values even if they are present. 

Passing -Dhttp.proxyHost and -Dhttp.proxyPort to java do not seem to make a difference.

**Comment by kevincdeng** [comment]
Thank you for the suggestion lambdaman. We will look into this.

**Comment by rrahul963** [comment]
is there a away to specify the proxy settings?

**Comment by rileymcdowell** [comment]
I am currently using a workaround to the lack of http proxy suport. I set up a SOCKS5 proxy on port 1080 in my local environment using an ssh tunnel to a machine that lives inside of an AWS VPC. The machine in AWS has unrestricted outgoing internet access. 

This means that I can append `-DsocksProxyHost=localhost -DsocksProxyPort=1080` to the java command locally and it will tunnel all http traffic out through the remote connection. I'm using the autossh utility to keep this SOCKS5 proxy connection open at all times.

You might assume that the http proxy versions of these java runtime flags would work without the need for configuring a SOCKS5 proxy. Unfortunately, passing `-DhttpProxyHost=<host_name> -DhttpProxyPort=<port_number>`  did not work for me, although these options are better documented in the java community than the socks variants.

**Comment by mscharp** [comment]
Has any support been added in the 3+ years this request has been opened?
