### ISSUE TITLE
Depend on explicit AWS SDK component projects

### ISSUE THREAD

**Issue by aztecrex** [awslabs/amazon-kinesis-client#25]
This project should depend on the necessary AWS SDK service-specific projects only.

The full SDK adds significant unneeded bulk to a deployment archive and increases the chance of dependency conflict in an application.

**Comment by kevincdeng** [comment]
Thank you for the suggestion aztecrex. We will look into this.

**Comment by pebo** [comment]
There is a PR that fixes this https://github.com/awslabs/amazon-kinesis-client/pull/20. Was this rejected for 1.4.0 and why were these new dependencies added?
+        <dependency>
+          <groupId>com.google.protobuf</groupId>
+          <artifactId>protobuf-java</artifactId>
+          <version>2.6.1</version>
+        </dependency>
+        <dependency>
+          <groupId>commons-lang</groupId>
+          <artifactId>commons-lang</artifactId>
+          <version>2.6</version>
+        </dependency>

**Comment by kevincdeng** [comment]
The PR will be merged in the next release. The new dependencies are for adding support for the Kinesis Producer Library.

**Comment by manango** [comment]
@aztecrex and @pebo, we have fixed this issue with KCL 1.5.0 release.
