### ISSUE TITLE
1.3.0 release on maven

### ISSUE THREAD

**Issue by dzsessona** [awslabs/amazon-kinesis-client#26]
Helllo, just a question, would the artifacts be uploaded to Maven Central? Thank you.

**Comment by dosani** [comment]
Hi @dzsessona, 

Thanks for checking. The artifacts have been uploaded to Maven, though it doesn't appear in the search yet. 

https://search.maven.org/#artifactdetails%7Ccom.amazonaws%7Camazon-kinesis-client%7C1.3.0%7Cjar

Thanks.
