### ISSUE TITLE
Gracefully handle stealing lease

### ISSUE THREAD

**Issue by csw244** [awslabs/amazon-kinesis-client#265]
Hi,

We have been seeing duplicate handling of stream due to stealing of leases. It is understandable that stealing of lease is required for even load distribution. However, would it be possible to gracefully steal lease? For example, can we wait until the lease has checkpoint, and then steal lease to avoid duplicate handling?

Thank you.

**Comment by sahilpalvia** [comment]
Checkpointing for the application is a feature that the KCL provides, but has no control over when to checkpoint in the application. That logic is controlled by the customers RecordProcessor. So, someone can checkpoint every few seconds to maybe every few minutes. There is no way for the KCL to know when the application is going to checkpoint. That is why it would be tough to steal leases gracefully. If the leases are being load balanced too frequently it means either your application is restarting too frequently or your worker is not renewing its leases. You can set the [`failoverTimeMillis`](https://github.com/awslabs/amazon-kinesis-client/blob/master/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/KinesisClientLibConfiguration.java#L937-L945) in your configuration, which sets the time within which a worker should renew a lease. Feel free to reopen the issue if you have more questions.
