### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by barbarosalp** [awslabs/amazon-kinesis-client#266]
Hello,

I am getting the exact error below. Any fix for this soon?

https://stackoverflow.com/questions/37734500/aws-kinesis-client-fails-with-java-lang-noclassdeffounderror

Thanks.

**Comment by pfifer** [comment]
What version of the library are you using?  The library supports, and uses the 1.11 version of the AWS SDK.

**Comment by sahilpalvia** [comment]
Closing issue, feel free to reopen if problem persists.
