### ISSUE TITLE
KCL does not appear to catch JsonParseException, halting operation of thread

### ISSUE THREAD

**Issue by andrewrosezen** [awslabs/amazon-kinesis-client#270]
From https://github.com/logstash-plugins/logstash-input-kinesis/issues/35#issuecomment-344953699

I've been experiencing an occasional situation in which the KCL stops attempting to retrieve messages from specified kinesis streams, and the only way I've been able to get the clients to resume has been via restarting them. It was mentioned in the referenced issue that this could be due to the KCL not catching JsonParseException and backing off.

**Comment by pfifer** [comment]
I responded on the linked issue.  This doesn't appear to be an issue with the KCL as JsonParseException is a checked exception which would need to be converted to a RuntimeException before being thrown from a method that doesn't declare the exception in its signature.  The conversion occurs within the AWS Java SDK.  

It's possible the problems you are seeing are related to #185.

**Comment by pfifer** [comment]
I'm going to close this, feel free to reopen if you have any more questions.
