### ISSUE TITLE
Open up the Worker

### ISSUE THREAD

**Issue by lc-nyovchev** [awslabs/amazon-kinesis-client#275]
What we have noticed with most AWS libraries, it's kind of okay to build fluent classes where all configuration options are honored and exposed.

However, if we were to already take an existing worker, all we can get about it is its application name.
In more ops-y environment, we want to have detection of number of assigned shards, shard prioritization, stream config, etc.

So, for example, we have a use case when we want to get the leaseCoordinator to list the current shard and it is not enough for use the log.debug that it provides in the private method.

Generally, my suggestion is to open the class a bit, exposing at least:

- ShardPrioritization
- KinesisClientLibLeaseCoordinator
- ShardSyncTaskManager
- IMetricsFactory (at least to get it, otherwise we'd have to keep an external reference to it)

Otherwise we'd have to extend the worker with our own implementations and it looks very messy, especially since everything is private and final.

EDIT:

Another thing that we are really looking forward to in a Spring environment, is to check when the actual worker has been fully initialized, with shard assignments and stuff. Right now we have code like this:

```
 private void initialize() {
        boolean isDone = false;
        Exception lastException = null;

        for (int i = 0; (!isDone) && (i < MAX_INITIALIZATION_ATTEMPTS); i++) {
            try {
                LOG.info("Initialization attempt " + (i + 1));
                LOG.info("Initializing LeaseCoordinator");
                leaseCoordinator.initialize();

                TaskResult result = null;
                if (!skipShardSyncAtWorkerInitializationIfLeasesExist
                        || leaseCoordinator.getLeaseManager().isLeaseTableEmpty()) {
                    LOG.info("Syncing Kinesis shard info");
                    ShardSyncTask shardSyncTask = new ShardSyncTask(streamConfig.getStreamProxy(),
                            leaseCoordinator.getLeaseManager(), initialPosition, cleanupLeasesUponShardCompletion, 0L);
                    result = new MetricsCollectingTaskDecorator(shardSyncTask, metricsFactory).call();
                } else {
                    LOG.info("Skipping shard sync per config setting (and lease table is not empty)");
                }

                if (result == null || result.getException() == null) {
                    if (!leaseCoordinator.isRunning()) {
                        LOG.info("Starting LeaseCoordinator");
                        leaseCoordinator.start();
                    } else {
                        LOG.info("LeaseCoordinator is already running. No need to start it.");
                    }
                    isDone = true;
                } else {
                    lastException = result.getException();
                }
            } catch (LeasingException e) {
                LOG.error("Caught exception when initializing LeaseCoordinator", e);
                lastException = e;
            } catch (Exception e) {
                lastException = e;
            }

            try {
                Thread.sleep(parentShardPollIntervalMillis);
            } catch (InterruptedException e) {
                LOG.debug("Sleep interrupted while initializing worker.");
            }
        }

        if (!isDone) {
            throw new RuntimeException(lastException);
        }
    }
```

and it would be nice to be able to get the state of isDone so we know when we have actually full started. Cause, of course, we start our Workers like this (so they don't block us indefinitely):

```
newSingleThreadExecutor()
    .submit(getWorker(muchStuff));
```

For now the simplest thing for us is to write a wrapper on the Worker into a Callable that 

- starts the worker
- polls the leaseCoordinator.isRunning() (with reflection, cause the Worker itself is extremely closed), and when it is done, it returns.

Instead of going through all these hoops, the worker can have a variable: State which we can poll.

**Comment by pfifer** [comment]
Thanks for the feedback, and for providing the PR.  I've looked at it, and had a few requests.
