### ISSUE TITLE
What should I assign to executableName in the KCL.Properties if the executable is a .Net core which is a dll not an exe

### ISSUE THREAD

**Issue by khaledsobhy83** [awslabs/amazon-kinesis-client#277]
I have a .Net Core implementation for the IRecordProcessor and not sure what should I assign to executableName in the KCL.Properties if my executable is built in  .Net core and is a dll not an exe and the way to execute it is through the command "dotnet dllname"?

**Comment by pfifer** [comment]
Depending on what platform you're on you could create either a shell script, or a batch file to execute the command.  The KCL just cares that the executableName can be executed, and communicates over standard in, and standard out.

**Comment by freeborn5** [comment]
So executableName = SampleConsumer.dll with the latest download?

**Comment by khaledsobhy83** [comment]
@freeborn5 did it work for you?

**Comment by freeborn5** [comment]
No - I realize that the Daemon must run for it to work.  In a
production environment how would that be set up ?

**Comment by khaledsobhy83** [comment]
Sorry for taking long to come back, I am not sure if I understood your question but in my KCL.properties file I am using this 
executableName = dotnet Consumer.dll
and it is working fine in production
