### ISSUE TITLE
Client side encryption for DynamoDB checkpointing

### ISSUE THREAD

**Issue by ClassicThunder** [awslabs/amazon-kinesis-client#279]
It would be helpful if client side encryption was an option for the DynamoDB checkpointing. We have data we are not allowed store in the cloud unencrypted, preventing us from being able to use the Amazon KCL.

**Comment by pfifer** [comment]
Thanks for the feedback.  We'll look into this, and will prioritize it against other requests we receive.

Others - Please comment or add your reaction to the parent post so our team is aware of how to prioritize this change.

**Comment by msiuts** [comment]
Would it be ok to just encrypt the table by default?

**Comment by klesniewski** [comment]
A workaround is to create the table with encryption enabled before worker is created. You can configure KCL to use the table with name of your choice.

**Comment by klesniewski** [comment]
DynamoDB encrypts now all tables by default, including the ones that were created in the past. Seems like this feature is then no longer needed.

https://aws.amazon.com/about-aws/whats-new/2018/11/amazon-dynamodb-encrypts-all-customer-data-at-rest/

**Comment by ClassicThunder** [comment]
Yup feature request no longer relevant.
