### ISSUE TITLE
Cannot stream with kinesis sample app

### ISSUE THREAD

**Issue by romangrewal** [awslabs/amazon-kinesis-client#304]
When running the c++ kinesis sample app with AWS_DEFAULT_REGION="us-east-1a"
it gives me the error
'Could not resolve host: kinesisvideo.us-east-1a.amazonaws.com'

When AWS_DEFAULT_REGION="us-east-1"
it gives me the error 
'The request signature we calculated does not match the signature you provided. Check your AWS secret access key and signing method'

What is the correct way to set up the kinesis sample app so that I can stream a sample video?

**Comment by sahilpalvia** [comment]
@romangrewal I think you are talking about the Kinesis Video Streams service. This repo is for the Kinesis Data Streams service. You may want to open an issue in the [amazon-kinesis-video-streams-producer-sdk-cpp](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp) repo.

Please feel free to reopen the issue if it is related to Kinesis Data Streams.
