### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by sheik5azmal** [awslabs/amazon-kinesis-client#32]
I want to use [Sourcegraph](https://sourcegraph.com) for amazon-kinesis-client code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/awslabs/amazon-kinesis-client. (It should only take 30 seconds.)

Thank you!

**Comment by kevincdeng** [comment]
I'll have to check with security and legal. I'll let you know once I hear back.

**Comment by kevincdeng** [comment]
Actually, it looks like anyone at all can enable it for public repos? Anyway, I've done so.
