### ISSUE TITLE
shutdownRequested method of IShutdownNotificationAware doesn't get called on shutdown

### ISSUE THREAD

**Issue by dhruvpanwar95** [awslabs/amazon-kinesis-client#322]
Whenever i stop my apllication gracefully,the shutdownRequested of IShutdownNotificationAware is not getting called.
Below is my code

@Service
public class MailBoltRecordProcessor implements IRecordProcessor,IShutdownNotificationAware {
///I do processing here
}

@Override
		public void shutdownRequested(IRecordProcessorCheckpointer arg0) {
			logger.info("helklllllll");
			checkpoint(arg0);
			// TODO Auto-generated method stub
			
		}

**Comment by dhruvpanwar95** [comment]
@pfifer Please help

**Comment by sahilpalvia** [comment]
Answered question in [Issue#35](https://github.com/awslabs/amazon-kinesis-client/issues/35#issuecomment-327597898).

Feel free to reopen the issue if the issue persists, or if you have more questions.
