### ISSUE TITLE
continuation of issue #323

### ISSUE THREAD

**Issue by hysmky** [awslabs/amazon-kinesis-client#324]
Dear Pfifer,

I tried to follow your suggestion on using the up-to-date version of KCL. Here are the two exceptions I suffered.
1- When I downloaded the code from git repository and used maven to build as suggested in the Readme, I got the following exception after succesfully downloading a series of files:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by lombok.javac.apt.LombokProcessor to field
com.sun.tools.javac.processing.JavacProcessingEnvironment.processorClassLoader
WARNING: Please consider reporting this to the maintainers of lombok.javac.apt.L
ombokProcessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflect
ive access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:20 min
[INFO] Finished at: 2018-04-06T23:22:49+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
2:compile (default-compile) on project amazon-kinesis-client: Fatal error compil
ing: java.lang.ExceptionInInitializerError: com.sun.tools.javac.code.TypeTags ->
 [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception
2- Then I decided to download the latest stable jar file from http://repo1.maven.org/maven2/com/amazonaws/amazon-kinesis-client/1.9.0/amazon-kinesis-client-1.9.0.jar and add it to the project. However, this time com.amazonaws.services.kinesis.clientlibrary.types.ShutdownReason, which is used by the Sample Code (see [here](https://docs.aws.amazon.com/streams/latest/dev/kinesis-record-processor-implementation-app-java.html)) can not be found.  Can you direct me to the KCL jar file which works with the lates AWS Java SDK*?
* I'm using 1.11.306

**Comment by pfifer** [comment]
I believe the sample code is out of date.  We moved `ShutdownReason` to a different package.  I'm not sure about the Maven issue.  What version of the JDK were you using?

**Comment by heysemkaya** [comment]
Thanks for response. I somehow found a workaround and finally KCL was working with updated sample code.
