### ISSUE TITLE
Overriding the default of MAX_INITIALIZATION_ATTEMPTS ?

### ISSUE THREAD

**Issue by idaamit** [awslabs/amazon-kinesis-client#329]
I would like the ability to influence the MAX_INITIALIZATION_ATTEMPTS.

**Comment by Dak0ta** [comment]
I have a pull request in for this already:

https://github.com/awslabs/amazon-kinesis-client/pull/316

**Comment by pfifer** [comment]
This was released for 2.0.1 as part of #368.  If there is specific requests we can look at back porting it to 1.9.x.
