### ISSUE TITLE
I want to pause a worker and wait for some time

### ISSUE THREAD

**Issue by akumariiit** [awslabs/amazon-kinesis-client#338]
Hi,
  This is not an issue but kind of question how to do it. below is the scenario:
I have 2 application consuming 2 different kinesis streams. I want to sync both applications, for that i am storing timestamps somewhere for both stream processing and checking periodically if difference is within allowed limit.

If not in limit, i am skipping process records method and doing nothing (no checkpointing), will kcl give me same records next time again if i have skipped them previously. I was thinking if there is any way to block processor thread until both applications are in sync, that would simplify it. Let me know if you need more clarification about the problem.

One more question:
  Does record processor factory in KCL in initialized one per application and it is responsible for creating processors for every lease?

**Comment by sahilpalvia** [comment]
I am not sure how are you synchronizing the work with multiple KCLs and streams. The KCL doesn't support the feature of pausing the ShardConsumer or Worker. Pausing the Worker/ShardConsumer could lead to more problems such as catching up to LATEST. The KCL uses the Checkpoint value when it loses a lease/at initialization to get the ShardIterator. Once you get a list of records from Kinesis using a ShardIterator, the KCL uses the ShardIterator from the response to get the next list of records. ShardIterators are valid for 5 mins from the time of creation, once they expire the KCL uses the last known sequence number to get a new ShardIterator. This is to ensure that the KCL is always making progress. 2 independent calls using the same checkpointed value could or couldn't return the same list of records, Kinesis doesn't guarantee that.

As for the IRecordProcessorFactory, the Worker is given the IRecordPrcoessorFactory. It will never initialize it. The IRecordProcessorFactory interface has a [createProcessor()](https://github.com/awslabs/amazon-kinesis-client/blob/master/src/main/java/com/amazonaws/services/kinesis/clientlibrary/interfaces/IRecordProcessorFactory.java#L28) method. This method is called by the [Worker](https://github.com/awslabs/amazon-kinesis-client/blob/master/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/Worker.java#L983-L1001) while creating a ShardConsumer. A ShardConsumer is created for each Shard lease owned by the worker.
