### ISSUE TITLE
Cannot Override DynamoDB Endpoint 

### ISSUE THREAD

**Issue by jnadler** [awslabs/amazon-kinesis-client#34]
We are using the excellent kinesalite (a light local mock of Kinesis for tests) to run automated integration tests.   All we have to do is set the endpoint ```withKinesisEndpoint("localhost:4567")```

When performing KCL operations against kinesalite, KCL is writing lease tables to our cloud DynamoDB.  We want our integration tests to run without touching our AWS account.

So,  I'd love to configure KCL to use a local mock of DynamoDB like dynalite.   This would require that KCL allow us to specify an endpoint for DynamoDB.

Possibly this would be analogous to withKinesisEndpoint:  ```withDynamoDbEndpoint("localhost:2345")```

**Comment by DVassallo** [comment]
You can construct your own AmazonDynamoDB client and update the endpoint with `setEndpoint("http://localhost:4567")`, and then construct the KCL Worker with the constructor that takes a custom AmazonDynamoDB client: 

https://github.com/awslabs/amazon-kinesis-client/blob/b596a0223ed59ce9f0b22b9495063f56aa7af2a4/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/Worker.java#L175-L189

**Comment by jnadler** [comment]
I missed that - works perfectly, thanks!

**Comment by letusfly85** [comment]
@jnadler 

How do you resolve cloudwatch client?
Do you have some good solutions like [kinesalite](https://github.com/mhart/kinesalite)?

**Comment by buremba** [comment]
If we set a region for client using KinesisClientLibConfiguration, the endpoint of DynamoDB client will be overridden. https://github.com/awslabs/amazon-kinesis-client/blob/master/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/Worker.java#L234

@letusfly85  I think it's OK to disable Cloudwatch client in tests so currently, we solve this issue with `kinesisConfig.withMetricsLevel(this.config.getEnableCloudWatch() ? SUMMARY : NONE)`

**Comment by letusfly85** [comment]
@buremba 

Thank you for suggestion!
I succeeded not to show warning on SBT console logs.

Thank you!
