### ISSUE TITLE
Enable property option to use AT_TIMESTAMP shard iterator in MultiLangDaemon clients

### ISSUE THREAD

**Issue by marcinc** [awslabs/amazon-kinesis-client#341]
Since support for Time based shard iterators was added in https://github.com/awslabs/amazon-kinesis-client/pull/94, it would be good to enable option to pass initial timestamp for `AT_TIMESTAMP` iterator from properties file. This would enable Multilang Daemon clients to take advantage of this iterator type. This was previously requested in https://github.com/awslabs/amazon-kinesis-client/issues/145.

It looks like it could be achieved by simply adding appropriate Date parameter type decoder in `KinesisClientLibConfigurator` which would then allow use of the following property: 
```
# app.properties

timestampAtInitialPositionInStream = 1527254694
```
Internally this would result in correct setting of `initialPositionInStream` to `AT_TIMESTAMP` and its initial timestamp to  `1527254694`.

**Comment by pfifer** [comment]
This should be fixed in 1.9.2 and should be available in Maven over the next 24 hours.

Feel free to reopen if you run into the issue again.
