### ISSUE TITLE
Question about UserRecord.deaggregate dropping records outside of EHK range

### ISSUE THREAD

**Issue by aheuermann** [awslabs/amazon-kinesis-client#343]
We have a setup where we have a lambda function pushing aggregated records to a kinesis stream and then that stream is consumed by a KCL Application. The lambda function is using the [awslabs/kinesis-aggregation library](https://github.com/awslabs/kinesis-aggregation) to create batched records.

We recently ran into an issue where a fair amount of records produced by the kinesis-aggregation library [were getting dropped in the KCL](https://github.com/awslabs/kinesis-aggregation/issues/11) due to the records in a given batch having EHK/PK outside the range of the shard. [The code in question is here](https://github.com/awslabs/amazon-kinesis-client/blob/master/src/main/java/com/amazonaws/services/kinesis/clientlibrary/types/UserRecord.java#L253-L259). To fix this we forced all records in a batch to have the EHK key of the first record in the batch.

I'm wondering what situation this logic in the KCL is handling? My only thought right now is that it is somehow related to splitting/merging, but the way I understand a split/merge is that new child shards are created, but ***existing*** data is not re-distributed to the new shards; instead, it cuts off writes to the old shards and directs writes to the new shards. I also read that the [KCL does not spin up new workers on a reshard until to parent shards are finished processing](https://github.com/awslabs/amazon-kinesis-client/issues/114#issuecomment-255404250).  So I'm thinking there is always a single worker per-shard. If these are true - that leads me to believe that this KCL logic to drop records may be un-necessary since all of the de-aggregated records came from a single put record. What are your thoughts?

I'm fairly new to Kinesis and the KCL so I am likely lacking some understanding, but wanted to get your thoughts.

Thanks!

**Comment by pfifer** [comment]
You're pretty much correct the only part is where the expected source of aggregated records is.  In this case the aggregated records are expected to originate from the [amazon-kinesis-producer](https://github.com/awslabs/amazon-kinesis-producer) (KPL).  

The KPL aggregates records by their expected shard destination.  When re-sharding occurs records destined for one of the parent shards will end going to the child shards.  When the KPL detects this it will refresh the shard map, and redistribute the records for the new shards.  The KPL is relying on the KCL deaggregation to discard the records that the KPL intends to retry

**Comment by pfifer** [comment]
I'm going to resolve this, feel free to re-open if you have more questions.
