### ISSUE TITLE
LeaseManager requires dynamoDb:CreateTable IAM permissions even if the table already exists.

### ISSUE THREAD

**Issue by ajbrown** [awslabs/amazon-kinesis-client#36]
The lease manager determines if the DynamoDb table already exists by attempting to create it, and ignoring a  `ResourceInUseException` .  This is non-optimal in an environment where the creation of resources is restricted, and the table has already been initialized.  

It would be more intuitive to use a DescribeTableRequest to determine if the table exists, since it's considered a read-only operation.

**Comment by pfifer** [comment]
A variant of this is now [committed](https://github.com/awslabs/amazon-kinesis-client/commit/8fc5dd5862b5daf777fad06c66d2a948e5caf9ad), and beginning the release process for it.

**Comment by pfifer** [comment]
The change is committed, and will be released soon on Maven.
