### ISSUE TITLE
Kcl can not consume data from shard (Stuck)

### ISSUE THREAD

**Issue by muhufuk** [awslabs/amazon-kinesis-client#361]
We have seen that our consumer application could not read data from shard, shard had data we are sure about it. Please have a look incoming and outgoingbyte in following image. (Blue one is outgoing and orange one is incomingbytes)

I have restarted application and It started to read data again.

![image](https://user-images.githubusercontent.com/18504514/43959705-6201c0d8-9cb8-11e8-834c-cd2a8ab354c0.png)

![image](https://user-images.githubusercontent.com/18504514/43959776-9e012bbe-9cb8-11e8-8d1d-e8a5c6c798bd.png)

After I restarted application, IteratorAgeMs graph is changed please have a look following image.

![image](https://user-images.githubusercontent.com/18504514/43959844-d82a8d58-9cb8-11e8-926a-352b5602cc2b.png)

We lost data because of this problem.
Can you help ? what is the root cause of this problem ? how can be sure that we wont face this problem again?

Our KCL version is name: 'amazon-kinesis-client', version: '1.8.7'

**Comment by jdmonter** [comment]
This looks the same as #185, which we've been battling with for months. We implemented the timeout after one hour to kill the container and respin. Less than ideal, but prevents data loss as the processor just picks up where it left off.

**Comment by pfifer** [comment]
In general this usually is the record processor getting blocked for some reason.  The KCL will wait for the record processor to return before retrieving, and processing the next batch of records.  We added a new [configuration option `logWarningForTaskAfterMillis`]( https://github.com/awslabs/amazon-kinesis-client/blob/v1.x/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/KinesisClientLibConfiguration.java#L1392) in [release 1.8.8](https://github.com/awslabs/amazon-kinesis-client/releases/tag/v1.8.8) which will log if a task has been blocked for more than the configured time.

If you see this is happening capturing successive stack dumps from the JVM may help discover what is blocked.  Stack traces can be captured using the jstack command, or sending the QUIT signal on POSIX systems.

**Comment by pfifer** [comment]
If you enable the configuration option it should log a message if there has been no progress for the number milliseconds specified.

**Comment by pfifer** [comment]
If the record processor blocks there isn't anything that the KCL can really do.  It doesn't know if the blocking behavior is intended.
