### ISSUE TITLE
KinesisClientRecord.data()

### ISSUE THREAD

**Issue by estebanroblesluna** [awslabs/amazon-kinesis-client#362]
Hi,
This is more an inquiry rather than an issue. I'm able to connect and start consuming records from Kinesis but when trying to read the data from the record it is unclear for me how to get it in a string.

I have tried to do the normal record.data().asCharBuffer().toString() but it doesn't give me the same result I'm obtaining from the command line.

Is the library already doing the Base64 decode for me?
Thanks
Esteban

**Comment by pfifer** [comment]
The in the KCL are in a [`java.nio.ByteBuffer`](https://docs.oracle.com/javase/8/docs/api/java/nio/ByteBuffer.html).  If you're used to using the CLI this is effectively the same as having been run through a Base64 decoder.

**Comment by estebanroblesluna** [comment]
OK got the issue. It is not uncompressing the data for me.

Solution:
byte[] arr = new byte[record.data().remaining()];
record.data().get(arr);

GZIPInputStream gis = new GZIPInputStream(new ByteArrayInputStream(arr));
BufferedReader bf = new BufferedReader(new InputStreamReader(gis, "UTF-8"));
String s = IOUtils.toString(bf);
IOUtils.closeQuietly(bf);

It would be nice that KinesisClientRecord as a convenient method to do this for us.
Thanks

**Comment by spicydoll** [comment]
use: String actualData = new String(record.getData().array());

**Comment by EKARavi** [comment]
i am also facing the same issue..i tried both but still no success'

//Approach 1
byte[] b = new byte[record.data().remaining()];
ByteBuffer byteBuf = record.data().get(b);
try {
	GZIPInputStream gis = new GZIPInputStream(new ByteArrayInputStream(b));
	BufferedReader bf = new BufferedReader(new InputStreamReader(gis, "UTF-8"));
	String s = IOUtils.toString(bf);
	IOUtils.closeQuietly(bf);
      } catch (Exception e) {
					e.printStackTrace();
				}
//Approach 2				
try {
	String actualData = new String(record.data().array());
       } catch (Exception e) {
					e.printStackTrace();
				}

////Approach 3				
String originalData = new String(byteBuf.array(), "UTF-8");

**Comment by EKARavi** [comment]
> OK got the issue. It is not uncompressing the data for me.
> 
> Solution:
> byte[] arr = new byte[record.data().remaining()];
> record.data().get(arr);
> 
> GZIPInputStream gis = new GZIPInputStream(new ByteArrayInputStream(arr));
> BufferedReader bf = new BufferedReader(new InputStreamReader(gis, "UTF-8"));
> String s = IOUtils.toString(bf);
> IOUtils.closeQuietly(bf);
> 
> It would be nice that KinesisClientRecord as a convenient method to do this for us.
> Thanks

its not working for me

**Comment by CraftingGamerTom** [comment]
What worked for me

Imports
```
import java.nio.charset.StandardCharsets;
```

Code
```
String dataAsAString = StandardCharsets.UTF_8.decode(record.data()).toString();
```
