### ISSUE TITLE
STSAssumeRoleSessionCredentialsProvider with external ID

### ISSUE THREAD

**Issue by jnewbigin** [awslabs/amazon-kinesis-client#367]
I am successfully using:
```AWSCredentialsProvider = STSAssumeRoleSessionCredentialsProvider|arn:aws:iam::<account_id>:role/<role_name>|<session_name>```

However I am now required to add an external id for the assume role.

`STSAssumeRoleSessionCredentialsProvider` does support this but there does not seem to be a way to pass it in via the `AWSCredentialsProviderPropertyValueDecoder`.

I am not a java expert so it may be that it is not obvious exactly how to do that.

Question 2:
If I must write my own custom provider to get this functionality, must I also use the com.amazonaws.auth. namespace in order for AWSCredentialsProviderPropertyValueDecoder to find it?

**Comment by jnewbigin** [comment]
I found the answer to Q2 by my self.

**Comment by jnewbigin** [comment]
I managed to get my requirement working by adding this class
```
package com.au.zzz;

import com.amazonaws.auth.AWSCredentialsProvider;
import com.amazonaws.auth.AWSSessionCredentials;
import com.amazonaws.auth.AWSSessionCredentialsProvider;
import com.amazonaws.auth.STSAssumeRoleSessionCredentialsProvider;
import com.amazonaws.auth.DefaultAWSCredentialsProviderChain;

public class ZZZCredentialsProvider implements AWSSessionCredentialsProvider {
        private STSAssumeRoleSessionCredentialsProvider provider;

        public ZZZCredentialsProvider(String roleArn, String roleSessionName, String roleExternalId) {
                provider = new STSAssumeRoleSessionCredentialsProvider.Builder(roleArn, roleSessionName).withExternalId(roleExternalId).build();
        }

        public AWSSessionCredentials getCredentials() {
                return provider.getCredentials();
        }

        public void refresh() {
        }
}
```

And then properties
`AWSCredentialsProvider = com.au.zzz.ZZZCredentialsProvider|arn:aws:iam::<account_id>:role/<role_name>|<session_name>|<external_id>`

**Comment by jnewbigin** [comment]
If AWSCredentialsProviderPropertyValueDecoder had some mechanism to use the Builder pattern rather than string constructors then we would not need to write custom java code.

**Comment by pfifer** [comment]
Thanks for reporting this.

We are currently working on the MultiLang Daemon for the 2.x release, and will be looking at making credentials creation easier.

**Comment by stair-aws** [comment]
(Please disregard the unintentional spam from force-pushing.)

Starting w/ KCL 2.5.2, you no longer need to author your own Java class(es) to set an external id. This can now be done by appending an optional nested property of `|externalId=<externalId>`. You can read more about this documented feature here: https://github.com/awslabs/amazon-kinesis-client/blob/master/docs/multilang/configuring-credential-providers.md
