### ISSUE TITLE
What happened to Worker in KCL v2.0?

### ISSUE THREAD

**Issue by emlyn** [awslabs/amazon-kinesis-client#382]
There doesn't seem to be a `Worker` class anymore, where has it gone and/or what are we supposed to use instead?

**Comment by sahilpalvia** [comment]
`Worker` has been replaced by `Scheduler`. You can find the migration document for migrating from 1.x to 2.x [here](https://docs.aws.amazon.com/streams/latest/dev/kcl-migration.

**Comment by Dak0ta** [comment]
Broken link? https://docs.aws.amazon.com/streams/latest/dev/kcl-migration

**Comment by sahilpalvia** [comment]
https://docs.aws.amazon.com/streams/latest/dev/kcl-migration.html

This is what it should have had been.

**Comment by pfifer** [comment]
It looks like we might have missed the change from Worker to Scheduler in the migration guide.  An [example of using the 2.x KCL](https://docs.aws.amazon.com/streams/latest/dev/building-enhanced-consumers-kcl-java.html) which may help in getting you started.

**Comment by emlyn** [comment]
Thanks, I had seen the migration guide, but as you say, it doesn't mention Worker/Scheduler. That example is useful though.

**Comment by sahilpalvia** [comment]
The documentation has been updated and the migration for the worker can be found [here](https://docs.aws.amazon.com/streams/latest/dev/kcl-migration.html#worker-migration).

Closing this issue, feel free to reopen the issue if problem persists.
