### ISSUE TITLE
Subsequent calls to processRecords with 0 records has incorrect largestPermittedCheckpointValue

### ISSUE THREAD

**Issue by rvestal37** [awslabs/amazon-kinesis-client#40]
In the case where some records are processed in one call, but NOT checkpointed, subsequent calls to the processRecords method with 0 records has the largest permitted value of the checkpointer set to the last checkpoint value and NOT the current largest value (which should be the largest permitted value from the last time processRecords was called with at least one record).

It looks like this is done in ProcessTask line 154 where if there are no records, the largest permitted value is set to the last checkpoint value instead of keeping its value from the last run.

If this is the expected/desired behaviour, how does a KCL application issue a checkpoint in subsequent calls to processRecords where there are 0 records (i.e. I get a few records, then after a minute or two decide it is time to do a checkpoint)?

If I store the last read record and use it for the checkpoint call, the RecordProcessorCheckpointer will throw during a checkpoint when 0 records were received because the record is not within the bounds of the last checkpoint and the largest permitted (which is the last checkpoint).

Thanks

**Comment by manango** [comment]
@rvestal37, thanks for reporting this issue. It has been fixed with the KCL 1.6.1 release.

**Comment by rvestal37** [comment]
Awesome, thanks for the fast turnaround!
