### ISSUE TITLE
Are lease tables ephemeral? 

### ISSUE THREAD

**Issue by owlab-exp** [awslabs/amazon-kinesis-client#414]
From the last week, I am trying to get data from DynamoDB tables by using DynamoDB Streams Kinesis Adapter + Kinesis Client Library. In my observations,
When I tried to consume by starting my application, I was able to see a new (lease)table created automatically and looked working, I mean my application was fed from new data from the table.
But If I shut down the application, the lease table was also destroyed automatically after a while.
Furthermore, sometimes the client suffered from errors - 400 Not Found Exception caused by the absence of its lease table and I found that the table disappeared at that times.
Is this normal? If it is normal, how can It continue consuming over multiple redeployments of my application?
I am using;
```
'com.amazonaws:aws-java-sdk:1.11.408'
'com.amazonaws:amazon-kinesis-client:1.9.2'
'com.amazonaws:dynamodb-streams-kinesis-adapter:1.4.0'
```
Thanks in advance!

**Comment by sahilpalvia** [comment]
The KCL does not have the capability to delete the lease table. I would suggest checking the application if it has the capabilities to delete the lease table.

**Comment by sahilpalvia** [comment]
Closing the issue out, feel free to reopen if problem persists.

**Comment by pkuoExpedia** [comment]
Saw the same problem too :'(
