### ISSUE TITLE
Worker gives up acquiring lease after 20 attempts.

### ISSUE THREAD

**Issue by tpounds** [awslabs/amazon-kinesis-client#42]
We ran into an issue today in which our Kinesis consumers failed to start after 20 attempts of acquiring a lease from DynamoDB which was related to an [AWS outage](https://aws.amazon.com/message/5467D2/). I took a look at the code and traced the issue to the following lines inside the Worker class.

https://github.com/awslabs/amazon-kinesis-client/blob/850db1a3dacea7be6d13f1bc57a49db960b6408d/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/Worker.java#L57
https://github.com/awslabs/amazon-kinesis-client/blob/850db1a3dacea7be6d13f1bc57a49db960b6408d/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/Worker.java#L321
https://github.com/awslabs/amazon-kinesis-client/blob/850db1a3dacea7be6d13f1bc57a49db960b6408d/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/Worker.java#L370

Is there any reason this constant is hardcoded to 20 attempts? It would be nice to configure it via constructor or setter injection. Even a global system property would be better than nothing.

**Comment by pfifer** [comment]
Thanks for reporting this.  We'll look at allowing configuration of the retry attempts.
