### ISSUE TITLE
Opt out of enhanced fanout mode in KCL 2.0

### ISSUE THREAD

**Issue by dlewis-n26** [awslabs/amazon-kinesis-client#429]
AFAIK, with KCL 2.0, enhanced fanout is turned on by default. Since one pays for enhanced fan-out by shard-hour, it would be great to b able to turn it off in the non-production environments to save costs. 

However, we were not able to find a configuration option in KCL 2.0 to opt out of enhanced fanout. Can we please add a toggle that allows this behaviour

**Comment by sahilpalvia** [comment]
KCL 2.x supports enhanced fan-out and polling as retrieval options. Polling uses [GetShardIterator](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_GetShardIterator.html) and [GetRecords](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_GetRecords.html) APIs. You can set the `RetrievalSpecificConfig` as `PollingConfig` in the `RetrievalConfig`, to opt-out of enhanced fan-out.

```java
PollingConfig pollingConfig = new PollingConfig(streamName, kinesisClient);
RetrievalConfig retrievalConfig = new RetrievalConfig(kinesisClient, streamName, applicationName).retrievalSpecificConfig(pollingConfig);
```

**Comment by dlewis-n26** [comment]
@sahilpalvia Thanks for the quick response. It would be great if this information gets added to the Kinesis documentation so that it is clear that this is the canonical way to opt-out of enhanced fan-out

**Comment by sahilpalvia** [comment]
Documentation has been updated. The information is provided under the `Without Enhanced Fan-Out` section. 

https://docs.aws.amazon.com/streams/latest/dev/building-enhanced-consumers-kcl-java.html

Closing the issue out. Feel free to reopen if problem persists.

**Comment by dlewis-n26** [comment]
@sahilpalvia Thank you

**Comment by rgarcia** [comment]
It'd also be great to have docs about how to do this using a `consumer.properties` config and `MultiLangDaemon`. Only through looking through the code is it possible to see that disabling fanout happens when you set one of these four configuration values:

1. retryGetRecordsInSeconds
2. maxGetRecordsThreadPool
3. idleTimeBetweenReadsInMillis
4. maxRecords

**Comment by jnewbigin** [comment]
`retrievalMode=POLLING`
looks like the correct way to use the non-fanout mode

**Comment by brianfife** [comment]
> Documentation has been updated. The information is provided under the `Without Enhanced Fan-Out` section.
> 
> https://docs.aws.amazon.com/streams/latest/dev/building-enhanced-consumers-kcl-java.html
> 
> Closing the issue out. Feel free to reopen if problem persists.

@sahilpalvia this documentation appears to be missing these days.

**Comment by asafsarid** [comment]
@sahilpalvia @jnewbigin 
Can you confirm that setting `retrievalMode=POLLING` in the config file works and will disable the enhanced fan-out mode?

**Comment by jnewbigin** [comment]
`retrievalMode=POLLING` is definitely working for me to disable enhanced fan-out.
It is case sensitive so must be exactly as written.

**Comment by naveen-nd** [comment]
@sahilpalvia how do we opt-out of enhanced fanout mode in amazon-kinesis-client-python?
