### ISSUE TITLE
KMS encrypted kinesis streams

### ISSUE THREAD

**Issue by agmen** [awslabs/amazon-kinesis-client#435]
Does this logstash plugin support KMS encrypted kinesis streams?
And if so, are there any examples of how it should be configured?

**Comment by pfifer** [comment]
This is probably better asked to logstash, as they may have stream creation support. 

If you're creating the stream you can enable encryption by calling [`StartStreamEncryption`](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_StartStreamEncryption.html) on the newly created stream.  Clients of Kinesis don't need to do anything different to use server-side encryption, so the logstash plugin should work normally.

The [Amazon Kinesis Developer Guide has more details about server-side encryption](https://docs.aws.amazon.com/streams/latest/dev/server-side-encryption.html)

Feel free to reopen this if you have more questions.
