### ISSUE TITLE
Why lots of methods are not undefined in 2.0?

### ISSUE THREAD

**Issue by FelixZhang1234** [awslabs/amazon-kinesis-client#441]
Lots of error messages like:
    'Description	Resource	Path	Location	Type
The method build() is undefined for the type KinesisClientLibConfiguration' when I important the project of KCL

**Comment by sahilpalvia** [comment]
`KinesisClientLibConfiguration` no longer exists for the 2.x version of the KCL. You can find the migration doc for 1.x to 2.x [here](https://docs.aws.amazon.com/streams/latest/dev/kcl-migration.html).

Closing the issue, feel free to reopen if problem persists.

**Comment by FelixZhang1234** [comment]
> `KinesisClientLibConfiguration` no longer exists for the 2.x version of the KCL. You can find the migration doc for 1.x to 2.x [here](https://docs.aws.amazon.com/streams/latest/dev/kcl-migration.html).
> 
> Closing the issue, feel free to reopen if problem persists.

Thank you very much.However, it's not just that this approach is problematic, and there's a lot of undefined content when I import the 2.0.2 version of the KCL into the eclipse.

**Comment by sahilpalvia** [comment]
Not sure what you mean by `undefined content`, could you clarify? If your application is depending on classes and packages from 1.x version of the KCL, you will see in the migration doc that `com.amazonaws` package no longer exists. The package structure has changed to `software.amazon`. Classes have changed too for eg: the equivalent class for `IRecordProcessor` interface has changed to `ShardRecordProcessor`. All of this information should be documented in the migration doc.

**Comment by FelixZhang1234** [comment]
> Not sure what you mean by `undefined content`, could you clarify? If your application is depending on classes and packages from 1.x version of the KCL, you will see in the migration doc that `com.amazonaws` package no longer exists. The package structure has changed to `software.amazon`. Classes have changed too for eg: the equivalent class for `IRecordProcessor` interface has changed to `ShardRecordProcessor`. All of this information should be documented in the migration doc.

I only download the 2.0.2 version of the KCL from the github, and there's lots of error message when I import the 2.0.2 version of the KCL into the eclipse, like: a lot of undefined methods,a lot of final fields may not have been initialized and so on.

**Comment by sahilpalvia** [comment]
That is probably because you are missing the lombok plugin. The KCL uses lombok to create constructors and other methods. IntelliJ has a lombok plugin, you may have to check if there is a similar plugin for eclipse.

**Comment by FelixZhang1234** [comment]
> That is probably because you are missing the lombok plugin. The KCL uses lombok to create constructors and other methods. IntelliJ has a lombok plugin, you may have to check if there is a similar plugin for eclipse.

That's a good idea, I will do it, you are great, thank you very much.
