### ISSUE TITLE
Worker goes idle forever

### ISSUE THREAD

**Issue by klesniewski** [awslabs/amazon-kinesis-client#442]
In one of our applications, we have observed that DynamoDB Streams processing sometimes stops until application is restarted. The first time it happened it caused quite a headache, as we discovered it more than 24 hours later (some data was no longer available in the stream). Now, with monitoring in place, we can see it happens every few days (happened 4 times so far). We have observed the following:

* It starts idling after reaching `SHARD_END` (not every time though). RecordProcessor is shut down with status `TERMINATE` and no new RecordProcessor is created. ShutdownTask does not report CreateLeases metrics, which it usually does.
* When idling, there is no RecordProcessor thread and worker repeatedly logs that it has `No activities assigned`. We can see in lease table that there is only one shard with checkpoint at `SHARD_END`. When refreshing the table, we can see that `leaseCounter` gets incremented. The TakeLeases and RenewAllLeases operations keep successfully running (by successfully I mean it reports success in metrics). LeaseTaker sees no new shards to take.
* After restart new shards are added to the lease table with checkpoint at `TRIM_HORIZON`, one is child of the shard with checkpoint at `SHARD_END` and parent of the other shard with `TRIM_HORIZON` checkpoint. The application resumes processing where it left off (or at oldest available data).

Checking KCL library implementation, we have noticed that LeaseTaker will take new leases only if these are available in the lease table. Discovering and inserting new leases to lease table happens only on 2 occasions: on worker initialization and on reaching shard end. We suspect that sometimes when shard end is reached and shards are listed, information about new shards is not yet available. Because of that, no new shards are inserted into lease table and so LeaseTaker will not see the new shards. As no shard is being consumed, no shard end is reached, no shards are ever inserted to lease table, and so the worker stays idle forever. Given there is more than one worker instance, the problem is probably less visible, since shards will be synced again when another worker finishes its shard, unlocking the idle worker. Nevertheless, there will be a period where worker is idle because shards are not in sync in lease table.

I am not sure, whether this issue belongs to KCL library or the DynamoDB Adapter. It seems KCL is working under assumption, that information about new shards is always available before shard end is reached. I don't know whether this assumption is intentional and violated by the Adapter, or whether the assumption is wrong and has to be fixed in KCL. Therefore I created this issue in both projects. The same issue in the other project: https://github.com/awslabs/dynamodb-streams-kinesis-adapter/issues/20

Libraries used:

* `com.amazonaws:dynamodb-streams-kinesis-adapter:1.4.0`
* `com.amazonaws:amazon-kinesis-client:1.9.0`

**Comment by pfifer** [comment]
Your investigation looks correct.  The KCL expects that when a shard has ended it's descendants should be available via DescribeStream/ListShards.  It does seem like the KCL isn't seeing the shards so it isn't creating the new leases.  

It looks like you have gotten a response on the other issue, so I'm going to close this in favor of awslabs/dynamodb-streams-kinesis-adapter#20.

Feel free to re-open this if you need more assistance.
