### ISSUE TITLE
Environment Configurability

### ISSUE THREAD

**Issue by czuares** [awslabs/amazon-kinesis-client#444]
My team would like to use the KCL in a container and provide dynamic properties to the MultiLangDaemon. 

Is there currently any way to specify/override properties like `streamName` via the environment or via the CLI using something like `-DstreamName=my-stream`? If not, would you consider expanding the implementation to support this?

**Comment by pfifer** [comment]
Thanks for providing this feedback.  We're currently planning to update the multilang daemon for KCL 2.0, and will prioritize this with other requested features.
