### ISSUE TITLE
ProcessRecords returning 0 records with records in stream

### ISSUE THREAD

**Issue by jonathantsao** [awslabs/amazon-kinesis-client#445]
To whom it may concern,

I'm currently using the Kinesis Client Library to consume records from a Kinesis data stream. However, when using the KCL, with ProcessRecords, KCL is pulling 0 records for specific shards. When monitoring the KinesisDataFetcher.getRecords.Success metric in CloudWatch, it seems to always be "successfully" calling GetRecords and even calling ProcessRecords.
However, outside of the context of KCL, when manually calling GetRecords using the Kinesis module from aws-sdk, we are able to receive records. 

We have 3 different consumers of the same stream. What is odd is that within a single shard, we'll receive 0 records for one consumer and non-zero records for another consumer.

We have also tried increasing the number of instances, but changing host machines and even running less shards/instance results in the same shard number receiving 0 records from KCL.

Some configurations:
We are running version 1.9.2.
failoverMillis: 60000
readIdleMillis: 5000
maxRecords: 10000
callProcessRecordsEvenForEmptyRecordList: true

What could be the reason why one particular shard isolated to one particular consumer could be receiving 0 records from the KCL even when there are records present in the stream and other consumers are successfully receiving records? Anything we can try?

Thanks
-Jonathan

**Comment by pfifer** [comment]
It's possible for readers to get 0 records.  This can occur if the application is at the tip of the shard and no new records have been put.  It can also occur if the application is behind, and is passing through a time when no records were present in the shard.  

All of you applications are independent of each other so they may be a different positions within the shard. [This forum post on the AWS Developer Forums](https://forums.aws.amazon.com/thread.jspa?threadID=199378&tstart=50) has more information about what may be happening.

Feel free to reopen this if you have more questions.

**Comment by jonathantsao** [comment]
In our case, there are new records that are constantly being put into the stream. But at some point the shard doesn't return any of the records and isn't able to recover, and eventually falls behind until it hits our retention period (24 hours).

This doesn't seem like the typical case where there is simply 0 records in the stream or some gap occurs. It seems to have entered some abnormal state where no records are ever received that the shard can't get out of.

**Comment by jonathantsao** [comment]
@pfifer Just wondering if you had any more insight on this issue.

It seems to have to do with a careful balance on the "readIdleMillis" parameter. We shortened it from 10 seconds to 5 seconds for one of our consumers, and the shard was able to catch up. However, another one of our consumers started to have the same issue on different shards altogether.

It's also could be worth noting that none are CPU constrained really.

**Comment by jonathantsao** [comment]
@pfifer So we have tried doing this, and it seems like the issue is still present, and has migrated over to other shards.

Via logs, we've also noticed that there a few shards that successfully call "processRecords" while sometimes receiving 1-5 records and sometimes receiving a 400-500 records, in an alternating pattern. These shards eventually fall behind because they aren't [receiving and] processing enough records fast enough. But it is evident that there are plenty of records in the stream to be received. It is also worth noting that on our "healthy" shards within the same type of ShardProcessor, "processRecords" is consistently being called with 400-600 records.

What determines the amount of records being received by "processRecords"?

**Comment by revanth1528** [comment]
Hi @pfifer ,

I've a similar issue , there are two consumers , one consumer X is continuously pushing the data to kinesis stream and three different consumers a,b,c(of different groups) are consuming this data. Sometimes I am experiencing a very strange issue that the three consumers a,b,c get 0 records every-time, but the strange thing is my metrics in cloudwatch/kinesis-dashboard will not show any lag in ```MillisBehindLatest``` property. 
I'm using kcl-2.2.9 and my configuration is. : 
```
 StaticCredentialsProvider staticCredentialsProvider = StaticCredentialsProvider.create( AwsBasicCredentials.create(accessKey, secretKey));
        KinesisAsyncClient kinesisClient = KinesisClientUtil.createKinesisAsyncClient(KinesisAsyncClient.builder().credentialsProvider(staticCredentialsProvider).region(Region.of(region)));
        DynamoDbAsyncClient dynamoClient = DynamoDbAsyncClient.builder().credentialsProvider(staticCredentialsProvider).region(Region.of(region)).build();
        CloudWatchAsyncClient cloudWatchClient = CloudWatchAsyncClient.builder().credentialsProvider(staticCredentialsProvider).region(Region.of(region)).build();
        ConfigsBuilder configsBuilder = new ConfigsBuilder(streamName, applicationName, kinesisClient, dynamoClient, cloudWatchClient,HOSTNAME, recordProcessorFactory);
        PollingConfig pollingConfig = new PollingConfig(streamName, kinesisClient);
        pollingConfig.recordsFetcherFactory().idleMillisBetweenCalls(60000L);
        ProcessorConfig processorConfig = configsBuilder.processorConfig();
        processorConfig.callProcessRecordsEvenForEmptyRecordList(true);
        pollingConfig.maxRecords(3000);
        RetrievalConfig retrievalConfig = new RetrievalConfig(kinesisClient, streamName, applicationName).retrievalSpecificConfig(pollingConfig);
        Scheduler scheduler = new Scheduler(
                configsBuilder.checkpointConfig(),
                configsBuilder.coordinatorConfig(),
                configsBuilder.leaseManagementConfig(),
                configsBuilder.lifecycleConfig(),
                configsBuilder.metricsConfig(),
                processorConfig,
                retrievalConfig
        );
        try {
            CompletableFuture.runAsync(scheduler);
        } catch (Throwable t) {
            log.error("Caught throwable while running scheduler for stream data : {} .",streamName, t);
        }
```

Please help me out here and let me know if i'm doing something wrong or missing something.
Thanks in advance.
