### ISSUE TITLE
I think it's throttling but how do i tell

### ISSUE THREAD

**Issue by jalateras** [awslabs/amazon-kinesis-client#46]
I am using the SDK with nodejs tp process records out of the kenisis streams. After about 4 or so hours i notice that the consumers are falling behind. I subsequently restart the process and it catches up. Then again, after sometime is slows down.

How can i tell from the logs, whether it is due to throttling or some other issue, maybe within my nodejs process.

Here are some of the more relevant settings

```
# Max records to fetch from Kinesis in a single GetRecords call.
maxRecords = 10000

# Idle time between record reads in milliseconds.
idleTimeBetweenReadsInMillis = 2000
```

I has a t look at the cloudwatch metrics, but i can't find a way to check that the consumers are being throttled.

The stream is configured with 3 shards

cheers
</jima>

**Comment by pfifer** [comment]
Kinesis now makes throttling metrics available.  You can tell if your stream is undergoing throttling by looking at the ReadProvisionThroughputExceeded metrics in the AWS Console.

Please feel free to reopen if you're still having problems.
