### ISSUE TITLE
KCL and Lambda

### ISSUE THREAD

**Issue by Nxtra** [awslabs/amazon-kinesis-client#466]
Can I use the KCL with AWS Lambda or is that not what it should be used for? I can find no examples of this use online and I wonder why?

**Comment by pfifer** [comment]
Lambda supports using [Kinesis as an event source](https://docs.aws.amazon.com/lambda/latest/dg/with-kinesis.html).  In theory it's possible to use the KCL with Lambda, but would be quite difficult in practice.

Feel free to reopen if you have more questions.
