### ISSUE TITLE
Too much INFO logs where DEBUG should suffice. Fix logging verbosity please!

### ISSUE THREAD

**Issue by rdsubhas** [awslabs/amazon-kinesis-client#47]
When running applications, it is very annoying to see unnecessary and necessary logs clumped together.

The following logs are really verbose and could be `DEBUG` level by default, and not `INFO` level:
- `DefaultCWMetricsPublisher` - every few seconds we get a log `Successfully published n datums` - These should be debug logs and not info in any way.
- `LogMetricsScope`
- `CWPublisherRunnable`
- `Worker` (do we really need info logs for sleep interruptions?)
- `MultiLangProtocol`

Similarly, Error messages could actually be printed as `log.error`, and not simple info. For example:
- `MessageWriter`
- `LeaseRenewer`
- `DrainChildSTDOUTTask`

**Comment by rdsubhas** [comment]
Hi, I raised this issue long back 😄 I can close if this is not relevant anymore

/cc @pfifer (sorry I saw your handle in the last commit so quickly checking if this is needed or not)

**Comment by kirillrdy** [comment]
I think this is already  fixed
