### ISSUE TITLE
pending checkpoint sequence numbers

### ISSUE THREAD

**Issue by sakrafd** [awslabs/amazon-kinesis-client#472]
Trying to understand and possibly incorporate pending checkpointing into my kcl v2.x consumer application and couldn't find much information as far as documentation or examples. Here is an example implementation:

```java
public class KinesisMessageConsumer implements ShardRecordProcessor {

  private PreparedCheckpointer preparedCheckpointer;
  
  @Override
  public void initialize(InitializationInput initializationInput) {
   if (initializationInput.pendingCheckpointSequenceNumber() != null && preparedCheckpointer != null) {
      preparedCheckpointer.checkpoint();
    }
  }

  @Override
  public void processRecords(ProcessRecordsInput processRecordsInput) {
    processRecordsInput.records().forEach(record -> {
      // process record 
    });
    if (shouldCheckpoint) {
        processRecordsInput.checkpointer().checkpoint();
    } else {
       preparedCheckpointer = processRecordsInput.checkpointer().prepareCheckpoint();
    }
  }
}
```
Is this the intended implementation? It seems to work when there is only one consuming app and a shard's lease is lost, but the initialize method can't checkpoint if the application is killed (or fails to checkpoint on shutdown) or in cases were there are multiple consumer applications and a different one steals the shard. Would it be possible to pass a checkpointer in the InitializationInput if there is a pendingCheckpointSequenceNumber?

Also, what's the added overhead of doing a prepareCheckpoint() for every message batch? How is this better than just calling checkpoint() (both are updating the dynamodb table)?

**Comment by pfifer** [comment]
The idea behind pending checkpoints is that it tells you that a previous process started to checkpoint, but was unable to complete the checkpoint.  This could be used to do things like rolling back a distributed transaction, or replaying the data to the exact same sequence number.

Feel free to reopen if you have more questions.
