### ISSUE TITLE
Unnecessary wait during scheduler initialization due to parentShardPollIntervalMillis sleep

### ISSUE THREAD

**Issue by bbeaudreault** [awslabs/amazon-kinesis-client#475]
According to the docs, `parentShardPollIntervalMillis` has the following effect:

```
/**
     * Interval in milliseconds between polling to check for parent shard completion.
     * Polling frequently will take up more DynamoDB IOPS (when there are leases for shards waiting on
     * completion of parent shards).
     *
     * <p>Default value: 10000L</p>
     */
```

But currently this property is being used in two ways:

1) [At Scheduler initialization time, to back off on initialization attempts](https://github.com/awslabs/amazon-kinesis-client/blob/master/amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/Scheduler.java#L271)

2) [During BlockedOnParent state](https://github.com/awslabs/amazon-kinesis-client/blob/master/amazon-kinesis-client/src/main/java/software/amazon/kinesis/lifecycle/ConsumerStates.java#L139)

The use-case of number 2 makes sense -- after a shard has split, it may take time for the parent to be drained. 

However use-case number 1 seems a little broken. It seems to be being used as a backoff timeout incase of retries. But the cost is being paid even if the first attempt was successful. We should either break out of the loop early, or use a different interval config if there is some other reason to wait here.

I was able to speed up my consumer start time by almost 10s by reducing parentShardPollIntervalMillis to 500ms. This means that in a sharding scenario or failure case I will be hammering dynamodb a bit. I've scaled my dynamodb to account for this, but I shouldn't have to. Instead the timeout should either be skipped after a successful attempt, or the timeout should get its own config variable.

**Comment by rehevkor5** [comment]
This also occurs during initialization even if the problem is due to an IAM permissions issue. Ideally, if it is a non-transient issue like an IAM issue, it would fail eagerly instead of retrying for multiple 10s periods.

**Comment by etspaceman** [comment]
This can be closed thanks to https://github.com/awslabs/amazon-kinesis-client/commit/3e32ff190687e7a34274923d36f640d337298c35

**Comment by bbeaudreault** [comment]
Thanks!
