### ISSUE TITLE
Processor behind and maxRecords set to 1000 on retrieval config yet only 300 records come back

### ISSUE THREAD

**Issue by BobbyJohansen** [awslabs/amazon-kinesis-client#477]
I have a record processor that is behind the tip of the stream, the max records on the retrieval polling config is set to 1000 however when logging the record count from ProcessRecordsInput in the record processor it only gives me around 250 to 300 records. Is there a reason why it does not grab 1000 at a time?

**Comment by sahilpalvia** [comment]
That configuration is for maximum number of records that can be returned in a GetRecords call. It doesn't mean it will return that many every time.

You can read the GetRecords API documentation [here](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_GetRecords.html).

Closing the issue. Feel free to reopen if problem persists.
