### ISSUE TITLE
Stable 2.0 release with STS support?

### ISSUE THREAD

**Issue by sammefford** [awslabs/amazon-kinesis-client#480]
AFICT, the 2.0.5 release depends on 2.0.6 packages of aws-sdk, which doesn't have a corresponding release of STS (it starts stable releases at 2.1.0 which isn't compatible with 2.0.6).  So if we need STS, we have to use a preview release and use trial and error to figure out which will work.  Any way the next release of KCL could be tested with STS?

To be specific, here's what I'm doing that requires a preview release of STS 2.x:

    private final ProfileCredentialsProvider profile = ProfileCredentialsProvider.builder()
        .profileName(profileName)
        .build();
    ...
        DynamoDbAsyncClient dynamoClient = DynamoDbAsyncClient.builder().region(region).credentialsProvider(profile).build();
        CloudWatchAsyncClient cloudWatchClient = CloudWatchAsyncClient.builder().region(region).credentialsProvider(profile).build();

**Comment by sahilpalvia** [comment]
KCL 2.1.0 has been released with SDK dependency of 2.2.0. This should solve your issue. Closing issue, please feel free to reopen if problem persists.
