### ISSUE TITLE
Support for create table requests to allow for BillingMode to be PAY_PER_REQUEST

### ISSUE THREAD

**Issue by degaydorus** [awslabs/amazon-kinesis-client#489]
In the latest version of amazon-kinesis-client (v2.1.0) I don't see a way to set a dynamo table's [billing mode](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/dynamodb/model/BillingMode.html) to the PAY_PER_REQUEST option.

For example a ProvisionedThroughputException would be thrown if read/write capacity is less than 1 here.  A client using this library wouldn't have a way to specify billing mode, instead it's assumed capacity units will be set or that a default capacity will be used.
https://github.com/awslabs/amazon-kinesis-client/blob/a88d4ba6027bbbf6445f1fa66001f90949dfe78a/amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/dynamodb/DynamoDBLeaseRefresher.java#L112

Since Billing Mode is supported in the latest aws java sdk, is support for this feature being planned for the amazon kinesis client?

**Comment by sahilpalvia** [comment]
Have you taken a look at using the [TableCreatorCallback](https://github.com/awslabs/amazon-kinesis-client/blob/master/amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/dynamodb/TableCreatorCallback.java). This class is only called if the table is newly created by the KCL.

You can set the newly create TableCreatorCallback in the [LeaseManagementConfig](https://github.com/awslabs/amazon-kinesis-client/blob/master/amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/LeaseManagementConfig.java#L232) and pass it to the Scheduler.

Closing the issue out, feel free to reopen if problem persists.

**Comment by degaydorus** [comment]
TableCreatorCallback says it's for post table creation which we can already do.  Is there something that can be _at_ table creation?

Converting a table from PROVISIONED mode to PAY_PER_REQUEST takes about 30-40 minutes, so we're trying to avoid that time with the ability to set PAY_PER_REQUEST from the beginning.

**Comment by wreulicke** [comment]
I would like to set PAY_PER_REQUEST from the beginning too.

**Comment by adrian-baker** [comment]
The lack of control over the DynamoDB resources that KCL creates is a major reason we actively try avoiding Kinesis. Between this issue and the inability to specify tags (https://github.com/awslabs/amazon-kinesis-client/issues/154), there's a lot of manual management to ensure that costs don't balloon over hundreds of over-provisioned, untagged orphaned tables.
