### ISSUE TITLE
Does KCL starts new worker if one goes down?

### ISSUE THREAD

**Issue by saeedansari** [awslabs/amazon-kinesis-client#499]
Hi,
We are running KCL v2.0.4 and we have a question about worker rescaling. Let's say two workers are running for two shards of a stream. If one of the worker goes down or get killed, does Scheduler automatically starts a new worker (or ShardConsumer) or this should be addressed in client code?

**Comment by sahilpalvia** [comment]
If the Scheduler goes down, it is on the application to handle restart for that Scheduler. If you have multiple Schedulers running on the same stream, the other Scheduler should pick up the leases that were being processed by the Scheduler which went down.

**Comment by saeedansari** [comment]
For a stream, Scheduler creates ShardConsumer per shard so a scheduler can start multiple ShardConsumer per stream depending on number of shards. My question is what happens if one of those ShardConsumers goes down? Does Scheduler start a new ShardConsumer to consume failed shard consumption?

**Comment by sahilpalvia** [comment]
ShardConsumers are Runnables that are scheduled on a thread pool. The ShardConsumer shouldn't go down normally. If the JVM has not been configured correctly, it can cause the ShardConsumer to have issues while running. In that case you will need to make sure that the JVM configuration is correct for the KCL to run correctly.

**Comment by saeedansari** [comment]
Is there any use case you can foresee which can lead to worker going down on its own or probably because of some misconfiguration or some exception while consuming events from the ShardConsumer?
one use case which we saw which would never happen to us in production is when we try to consume from our application in our network(we need to authenticate using the AWS credentials which has expiry.) In that case when the credentials get expired the worker goes down.

Can you think of any other use case which we can have, which could lead to worker going down like this use case ?

**Comment by sahilpalvia** [comment]
The KCL mostly is resilient enough to retry on failures. The KCL handles failure scenarios and avoids threads from dying in flight. So as you mentioned the network scenario, the KCL would fail but would handle the failure and keep on retrying.

Please feel free to close the issue out if the problem has been resolved.
