### ISSUE TITLE
Possible New Updates

### ISSUE THREAD

**Issue by ajreid21** [awslabs/amazon-kinesis-client#5]
1. It would be nice to have a setting to force child shard(s) to be processed by the same app instance that was processing the parent shard(s) after a split/merge.
2. Would it be possible to have the kinesis client library balance OPEN shards explicitly across app instances (instead of treating closed and open shards the same). Issue is that it is possible for an app instance to get and have to process all the OPEN shards and the other to sit there idle with leases just on closed shards.

Thoughts?

**Comment by pfifer** [comment]
It looks like there is the same suggestion in #78 for this.  

Please reopen if you're still seeing an issue with 2.
