### ISSUE TITLE
Best way to deal with "hot" workers?

### ISSUE THREAD

**Issue by samcday** [awslabs/amazon-kinesis-client#50]
Background: we have a KCL app running in an autoscaling group that is currently spread across 5x `c3.large` instances. Our Kinesis stream is 32 shards, but our actual average volume in records is around 7-10k per second. There's a reason why we have such a silly amount of over-provisioned shards. But it's not very interesting and probably not relevant to the issue at hand.

So anyway, in the same way that DynamoDB and Kinesis best practices are modelled around producers / writers avoiding "hot" partitions at all costs, we've now discovered that KCL needs something similar. The problem is KCL seems to naively assign leases to workers by simply ensuring all active workers have an "even" number of shards. The problem with this is that shards are not all equal :)

Let's work off a contrived example. Let's say we have a 10 shard Kinesis stream being processed by 2 KCL Worker instances (on separate machines). Once everything is running it'll kinda look like this:

```
Worker 1: { Shard 1, 2, 3, 4, 5}
Worker 2: { Shard 6, 7, 8, 9, 10}
```

This looks "balanced", right? Sure. But now imagine that for whatever reason, shards 1, 2, 3, 4, 5 are receiving about 1000 incoming records a second, but the other 5 shards are only getting 10 a second. This now means the actual number of incoming records flowing into the workers kinda looks like this:

```
Worker 1: 5000 incoming records per second
Worker 2: 50 incoming records per second
```

As a result, you can end up with 1 worker doing 100x more work than the other worker. Like I mentioned earlier, we have our KCL worker app in an autoscaling group that automatically scales up based on average CPU usage across all running instances. The problem is in a larger instance of the described issue, you'll end up with 1-2 instances doing 2-3x more work than the others, and as a result are pegging their CPU. But, this isn't enough to set the average CPU over the edge to bring more instances up.

It seems like KCL should be able to balance work across instances not just using a naive "number of leases" approach, but perhaps *weight* these leases by the actual amount of work they're receiving? Maybe if the workers were reporting the average volume of records they're receiving per minute for the last 15 minutes into the lease table, that could be used to redistribute as necessary?

**Comment by darkcrawler01** [comment]
this is an interesting problem .. 
but i would recommend a more evenly distributed partition key ..
If that is not an option, perform `SplitShard` on the "hot" shards until a point the data is evenly distributed.. Shard splitting allows more shards for the same hash key range, thereby workers can split work .. 

IMO its best to treat the KCL workers as nodes in a proper distributed system. Each node does the same amount of work as its peers and thereby can scale almost infinitely.
Hope it helps

**Comment by samcday** [comment]
Thanks @darkcrawler01 :)

**Comment by avram** [comment]
Is your size of work per shard at least scaled to the width of keyspace? Since making lease count be scaled by keyspace width per shard makes a lot of sense.

**Comment by az3** [comment]
I agree with avram, it might be related to HashKeyRange of each shard.
Please see https://github.com/awslabs/amazon-kinesis-client/issues/56
