### ISSUE TITLE
Options for lease table creation (DynamoDB)

### ISSUE THREAD

**Issue by komamitsu** [awslabs/amazon-kinesis-client#509]
I want to make a lease table created by KCL on DynamoDB auto scaling. But KCL doesn't seem to support it.

So, I think there are these 4 options
1. Make it possible to make a DynamoDB table auto scaling by KCL (new feature)
2. Delegate the table creation and configuration to a provisioning tool like Terraform. But I want to make sure that KCL doesn't create a new lease table by itself. It looks `DynamoDBLeaseCoordinator#initialize` always tries to create a lease table if it doesn't exist. So it would be great if we can disable the KCL's implicit lease table creation (new feature)
3. Almost same as the above option#2. But let our Kinesis consumer application fail to start if the lease table doesn't exist
4. Let our Kinesis consumer application check the config of the lease table and make the lease table auto scaling by itself

It seems the option#1 is the best for application developers. The option#2 would be good enough. But we have a plan to go with the option#4 for now.

My question (and requirement) is
- Do you have a plan to support the option#1 or 2?
- Do you think the option#3 is safe?

**Comment by sahilpalvia** [comment]
KCL v2.x supports post table creation support for modifying the DynamoDB table. You can implement an autoscaling version of the [TableCreatorCallback](https://github.com/awslabs/amazon-kinesis-client/blob/master/amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/dynamodb/TableCreatorCallback.java). This only gets called when DynamoDB is created. You can set your autoscaling post table creator callback in the [LeaseManagementConfig](https://github.com/awslabs/amazon-kinesis-client/blob/master/amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/LeaseManagementConfig.java#L232).

The other thing is, it is not required for the KCL to create the table. You can create the table and pass in the table information to the KCL, and it will use the required table.

Closing out this issue, please feel free to reopen if problem persists.
