### ISSUE TITLE
idleTimeBetweenReadsInMillis does not seem to be respected

### ISSUE THREAD

**Issue by elrob** [awslabs/amazon-kinesis-client#515]
- With default configuration below except for `idleTimeBetweenReadsInMillis`, it appears to not be respected.
- Even with idle time set to 10 seconds below, I see that the `ShardRecordProcessor` is being called multiple times within a 10 second period:
    ```
    2019.03.13 05:51:31 [ShardRecordProcessor-0001] INFO  StreamRecordProcessor ...
    2019.03.13 05:51:36 [ShardRecordProcessor-0001] INFO  StreamRecordProcessor ...
    2019.03.13 05:51:37 [ShardRecordProcessor-0001] INFO  StreamRecordProcessor ...
    ```
- When I attempt to follow the source code through, it appears as though the value is never read from `PollingConfig`?

```java
        KinesisAsyncClient kinesisClient = KinesisAsyncClient.builder().build();
        DynamoDbAsyncClient dynamoClient = DynamoDbAsyncClient.builder().build();
        CloudWatchAsyncClient cloudWatchClient = CloudWatchAsyncClient.builder().build();
        ConfigsBuilder configsBuilder = new ConfigsBuilder(streamName, applicationName, kinesisClient, dynamoClient, cloudWatchClient, UUID.randomUUID().toString(), streamRecordProcessorFactory);
        Scheduler scheduler = new Scheduler(
                configsBuilder.checkpointConfig(),
                configsBuilder.coordinatorConfig(),
                configsBuilder.leaseManagementConfig(),
                configsBuilder.lifecycleConfig(),
                configsBuilder.metricsConfig(),
                configsBuilder.processorConfig(),
                configsBuilder.retrievalConfig().retrievalSpecificConfig(
                        new PollingConfig(streamName, kinesisClient)
                                .idleTimeBetweenReadsInMillis(Duration.ofSeconds(10).toMillis())
                )
        );
```

Version:
```xml
        <dependency>
            <groupId>software.amazon.kinesis</groupId>
            <artifactId>amazon-kinesis-client</artifactId>
            <version>2.1.2</version>
        </dependency>
```

**Comment by vtlkvl** [comment]
We are observing the same issue.

**Comment by vtlkvl** [comment]
It seems like `pollingConfig.recordsFetcherFactory().idleMillisBetweenCalls(Duration.ofSeconds(10).toMillis())` should work.

**Comment by asanthan-amazon** [comment]
It seems the below code should work ideally.

new PollingConfig(streamName, kinesisClient)
                                .idleTimeBetweenReadsInMillis(Duration.ofSeconds(10).toMillis())

Looks like a bug in the code that does not use idleTimeBetweenReadInMillis variable.

**Comment by praetp** [comment]
Seems this problem is still present ?

**Comment by odoric27** [comment]
doesn't seem like there's a way to do this with `idleTimeBetweenReadsInMillis` in kcl 2.x, but [this](https://docs.aws.amazon.com/streams/latest/dev/kcl-migration.html#idle-time-removal) suggests there is a another way via `CoordinatorConfig#shardConsumerDispatchPollIntervalMillis`

**Comment by praetp** [comment]
Actually @vtlkvl 's solution works, I found out.

**Comment by ayerrag1** [comment]
We are observing same with the maxRecords setting too. Below is my code. 
`PollingConfig pollingConfig = new PollingConfig(streamName,kinesisClient).maxRecords(25);`
`		<dependency>
			<groupId>software.amazon.kinesis</groupId>
			<artifactId>amazon-kinesis-client</artifactId>
			<version>2.3.0</version>
		</dependency>
`

**Comment by akidambisrinivasan** [comment]
With the merged fix (once it is released), the recommended way to configure idleTimeBetweenReadsInMillis is as follows:

```
configsBuilder.retrievalConfig().retrievalSpecificConfig(
   new PollingConfig(streamName, kinesisClient)
       .idleTimeBetweenReadsInMillis(Duration.ofSeconds(10).toMillis())
```
