### ISSUE TITLE
Support for Android

### ISSUE THREAD

**Issue by loretoparisi** [awslabs/amazon-kinesis-client#52]
Is it possible to run this Java client on Android 23? I cannot use the AWS Android SDK due to too many dependencies. I only need the kinesis stream, without any `cognito` identity, I'm doing anonymous login.

**Comment by pims** [comment]
@loretoparisi this is a high level wrapper around the AWS Kinesis SDK, so if you can't use the AWS Android SDK, it’s likely you won't be able to use the KCL.

What you could do is sign a url and have your clients just POST records to it.

**Comment by loretoparisi** [comment]
@pims so is it possibile to use like a REST API?

**Comment by pfifer** [comment]
There isn't a way to run the KCL without using the SDK.  Are you intending to process Kinesis data on the Android device, or do you just want to publish data to Kinesis from Android devices?

If you only want to publish data from Android to Kinesis you might be able to use [Amazon API Gateway](https://aws.amazon.com/api-gateway/).  This would allow you to create a REST API that could call Kinesis' PutRecord operation.

I'm going to close this for now, but if you're interested in using API Gateway and want some more information I would recommend posting on the [Amazon API Gateway Forums](https://forums.aws.amazon.com/forum.jspa?forumID=199) or on the [Amazon Kinesis Forums](https://forums.aws.amazon.com/forum.jspa?forumID=169).  If you have any other questions about the KCL feel free to reopen this.

**Comment by loretoparisi** [comment]
@pfifer Thanks, the need was for to publish data from an android app directly.
