### ISSUE TITLE
Custom checkpointing logic

### ISSUE THREAD

**Issue by buremba** [awslabs/amazon-kinesis-client#53]
We have a data processing engine that reads data from Kinesis, it has two separate jobs: continuous aggregation based on pre-defined rules and sending raw data to our database engine in micro-batches.

Currently, we use KCL to read data from Kinesis but the checkpointing is tricky since we have two jobs that are independent from each other. Continuous aggregation should be done in real-time while we can tolerate some delay for queries that we execute on our database engine.

Also, if we checkpoint after this two jobs are done, it's possible that a node may fail when it's done only one of the jobs which may cause some inconsistency of the data.

We may have independent consumers for each job but it would come with an overhead. Since KCL uses dynamodb for checkpointing, I wonder if it's possible to use a custom checkpointing logic for this use case.

**Comment by IanMeyers** [comment]
It sounds like if you set two different application names in the KinesisClientLibConfiguration, you should get the behaviour you are looking for. Both applications will checkpoint individually and no additional coordination will be required.

**Comment by buremba** [comment]
@IanMeyers AFAIK KinesisClientLibConfiguration can only have one application name. If you mean that I should construct two different Worker instances with two different application names configured in KinesisClientLibConfiguration, then I would have two independent consumers fetching data from Kinesis. It doubles the network operations and since they're independent, the deserialization should be done twice for each consumer, right?

**Comment by IanMeyers** [comment]
Yes exactly that - run the two jobs in two separate workers if you want to decouple the checkpointing. You are correct that this will then be two reads from the stream for a single record. I'll defer to the kinesis team regarding other features you are requesting.

**Comment by buremba** [comment]
@IanMeyers, thanks!

**Comment by IanMeyers** [comment]
Also, just food for thought - let's say you stay with one worker that could checkpoint 2 application names separately, and it crashes. When it crashes, maybe you have correctly checkpointed one application, but not the other. Then when you start the worker again, what sequence should the worker start reading the stream from? The older of the 2 last checkpoint sequences? The later? 

In any case you will end up processing some records more than once, which obviates having independent checkpointing at all. You instead need to be sure that you can idempotently process the records, at which point you don't need to worry that the checkpointing is a single high water mark. 

Also, by having two logical applications from one stream deserialisation, you create a case where both jobs can only ever run as fast as the slowest. Again, having separate workers addresses this. 

HTH,

Ian

**Comment by buremba** [comment]
Currently, I have two workers. The first one that does the continuous aggregation fetches the records in real-time, and put them in a buffer. Based on the count of records and the last flush time (a small interval like 10s), we flush the buffer, deserialize the records and update the aggregation state. Then we checkpoint the position. it's the usual use case.

The other worker sets 1 minute as the value of idleTimeBetweenReadsInMillis config to avoid buffering. KCL fetches the records periodically in each minute, the application deserializes the records as soon as they are arrived and store them in our database engine.

I think the problem you addresses can be solved using different contexts in worker instances. The application code will use two different IRecordProcessor but the IRecordProcessorCheckpointer instances will be belong to the same worker but use different namespaces. Also the deserialization should be embedded in KCL since the library itself should deserialize the records once and send them to record processors in order to avoid extra deserialization cost. 

In the scenario you described, if a node fails, the library can look at DynamoDB table to decide which record processor instances must process the records based on the applications committed the records.
