### ISSUE TITLE
Can a record be read from a Kinesis stream without removing it?

### ISSUE THREAD

**Issue by danotorrey** [awslabs/amazon-kinesis-client#555]
In our application, we are developing a "test" feature, which allows a user to test the Kinesis connection that they are setting up. 

We are wondering if there is a way to read a message from a Kinesis stream without removing it from the stream? We just want to temporarily retrieve a message and make sure it is valid, but we don't want the message to be lost.

I have see the [KCLv2 read example](https://docs.aws.amazon.com/streams/latest/dev/kcl2-standard-consumer-java-example.html), but can't tell if it supports this

**Comment by casret** [comment]
Messages stay in the stream for (default) 24 hours, they are removed when they expire, not through the act of consuming them.  That said, the KCL library is really tuned to deliver you every message only once.  The checkpointing feature might work for you, but it's hard to say without knowing more details.  You may be better off using the Kinesis API directly during the 'testing' phase.

**Comment by danotorrey** [comment]
@casret This all makes sense and helps a lot. Thank you!
