### ISSUE TITLE
Use HashKeyRange To Distribute Shards Among Consumer Applications

### ISSUE THREAD

**Issue by az3** [awslabs/amazon-kinesis-client#56]
Hello,

The shard distribution to each worker nodes should be calculated in terms of HashKeyRanges.

Explanation below;

At the moment, KCL redistributes shards amongst consumer applications equally. That is,
- If you have 10 shards, and 1 consumer application with 2 instances, each instance will have 5 shards leased.

This is good, when the shards listen to same hash ranges. Good scenario is shown below;

```
Name    HashSt  HashEnd Instance
Shard00 00001   03402   worker1
Shard01 03403   06804   worker2
Shard02 06805   10206   worker1
Shard03 10207   13608   worker2
Shard04 13609   17010   worker1
Shard05 17011   20412   worker2
Shard06 20413   23814   worker2
Shard07 23815   27216   worker1
Shard08 27217   30618   worker1
Shard09 30619   34020   worker2
```

Both workers listen to 5 shards, and equal hash ranges.

But, if we split Shard00 into two (10 and 11), then Shard11 into two again, the distribution may change into something like this;

```
Name    HashSt  HashEnd Instance
Shard10 00001   01701   worker1
Shard12 01702   02552   worker2
Shard13 02553   03402   worker1
Shard01 03403   06804   worker1
Shard02 06805   10206   worker2
Shard03 10207   13608   worker1
Shard04 13609   17010   worker2
Shard05 17011   20412   worker2
Shard06 20413   23814   worker1
Shard07 23815   27216   worker1
Shard08 27217   30618   worker2
Shard09 30619   34020   worker2
```

Here, both workers listen to 6 shards each, but their weights are different (in terms of hash ranges). So when producers feed this stream in a randomly balanced partiton keys, the number of data processed in each worker node will be different. That may cause unbalance.

Regards,
Cagri.

**Comment by darkcrawler01** [comment]
@az3 we always split all the shards at the same time.. 
so the capacity increases/decreases by power of 2 and the work is evenly distributed between the shards.

**Comment by pfifer** [comment]
Thanks for suggesting this.  This is something that I could see be useful for a more dynamic approach to load, but I would generally recommend following @darkcrawler01's advice.  Having balanced hash key ranges can ensure that incoming data is spread evenly across all the shards.  

We will prioritize this request against other customer requests we receive.

Others - Please comment or add your reaction to this post so our team is aware of how to prioritize this change.
