### ISSUE TITLE
ERROR: Unable to parse HTTP response content (request cut - empty body)

### ISSUE THREAD

**Issue by pkopac** [awslabs/amazon-kinesis-client#57]
Something with the lease. It logs this error I'm attaching, but then it seems to continue processing OK. I don't know, whether it skipped any data.

[app.txt](https://github.com/awslabs/amazon-kinesis-client/files/124432/app.txt)

(We have alerts on ERRORs, so if it can recover, it should be logged as WARN only)

**Comment by bgdnlp** [comment]
I got the same error at first.

Check your settings for the endpoints the config file. In my config there was a setting for kinesis endpoint and one for firehose. The docs don't mention the kinesis one, but they do mention cloudwatch, so I had kinesis endpoint set to "monitoring.eu-west-1.amazonaws.com".

It should be something like:
  "cloudwatch.endpoint": "monitoring.eu-west-1.amazonaws.com",
  "kinesis.endpoint": "kinesis.eu-west-1.amazonaws.com",
  "firehose.endpoint": "firehose.eu-west-1.amazonaws.com",

**Comment by pfifer** [comment]
This error is emitted by the AWS Java SDK, so is not directly controlled by the KCL.  It appears the class may have been removed in newer versions of the SDK, and this may longer be a problem.

Feel free to reopen if you are still having problems.
