### ISSUE TITLE
Question: Listen mutliple Steam and use One dynamoTable

### ISSUE THREAD

**Issue by ndaussy** [awslabs/amazon-kinesis-client#578]
Context:
One application should listen at least two stream.
I have an issue to run both Kcl listener in same app.
I see only two entry in my table whereas i have 4 shards ( 2 by stream ).

Questions :
How many entry should i have in my table ? 4/2 ?
Is it possible to do it without declaring for each stream one dedicated table in dynamoDb ?
If it's not possible, why ? ^^ Bad pratice ? Or KCL limit ?

**Comment by sahilpalvia** [comment]
One KCL worker only supports one stream per application. You could have multiple workers running under the same JVM, but sharing resources across multiple workers under the same JVM is not recommended.

Closing the issue out. Please feel free to reopen if problem persists.
