### ISSUE TITLE
Multi-lang daemon not respecting executableName flags/args

### ISSUE THREAD

**Issue by aaronkavlie-wf** [awslabs/amazon-kinesis-client#58]
If you set the `executableName` in the properties file to something with flags or args like so:

``` properties
executableName = ./consumer --debug
```

things at first appear to be fine:

```
INFO: Running foo to process stream bar with executable ./consumer --debug
```

but later in the logs:

```
INFO: MultiLangDaemon is adding the following fields to the User Agent: amazon-kinesis-client-library-java-1.6.1 amazon-kinesis-multi-lang-daemon/1.0.1 Golang ./consumer
```

the code is dropping everything after the first space [here](https://github.com/awslabs/amazon-kinesis-client/blob/c6e393c13ec348f77b8b08082ba56823776ee48a/src/main/java/com/amazonaws/services/kinesis/multilang/MultiLangDaemonConfig.java#L122-L125).

I wasn't able to pin down where exactly it spawns the process, but in my testing it does seem to run without regard for any flags or args you supply.

**Comment by pfifer** [comment]
Thanks for reporting this.  We are investigating this bug.

**Comment by pfifer** [comment]
The MultiLang Daemon does start the application with the command line parameters, but doesn't apply the command lines parameters to the user agent.  Is there a reason you want the command line parameters as part of the user agent string?

**Comment by aaronkavlie-wf** [comment]
It's not clear to me what you mean by "user agent" as opposed to "application" here (I mostly hear "user agent" with regard to browser user agent strings).

FWIW I'm not actively using the KCL at this time, though I may again for a current project.

**Comment by pfifer** [comment]
The code you linked to is about setting the user agent, which is used when sending requests to Kinesis. 

The actual process launch occurs at [MultiLangRecordProcessorFactory.java#L57](https://github.com/awslabs/amazon-kinesis-client/blob/master/src/main/java/com/amazonaws/services/kinesis/multilang/MultiLangRecordProcessorFactory.java#L57).  So it should be launching the child process with the correct command line parameters.

**Comment by aaronkavlie-wf** [comment]
Ah. Yeah, it's been a while...

I don't remember for sure whether or not I confirmed that the actual program was (or was not) running with the `--debug` flag set. It could be that I saw that message, and thought that the tail end was suggesting that it was running `./consumer` with no flags.

**Comment by pfifer** [comment]
Sorry for the long delay in responding.  

The confusion makes sense since it logs the apparent command in two different places, and neither of those is when it actually starts spawns the command.

Please feel free to reopen if you have any additional questions.
