### ISSUE TITLE
KCL 2.2.2 has a bug that will cause polling readers to get stuck 

### ISSUE THREAD

**Issue by ashwing** [awslabs/amazon-kinesis-client#602]
KCL 2.2.2 has a bug that will cause **Polling** readers to get stuck in the event of executor service failure.

In 2.2.2 release, a lock was introduced in the polling publisher class [PrefetchRecordsPublisher](https://github.com/awslabs/amazon-kinesis-client/blob/master/amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/polling/PrefetchRecordsPublisher.java#L253) to prevent data loss. 

Now, when data loss happens in the executor service, the reader is getting stuck without making further progress, and not giving control back to the error handler.

We are actively working on a fix for this issue.

**Comment by ashwing** [comment]
https://github.com/awslabs/amazon-kinesis-client/pull/603

**Comment by ashwing** [comment]
External release now available for this fix

```
<dependency>
  <groupId>software.amazon.kinesis</groupId>
  <artifactId>amazon-kinesis-client</artifactId>
  <version>2.2.3</version>
</dependency>
```

**Comment by ashwing** [comment]
Let's close this issue once internal release is completed

**Comment by micah-jaffe** [comment]
KCL Release 2.2.3 is complete. Resolving this issue.
