### ISSUE TITLE
shard shutdown can not properly checkpoint at shard end

### ISSUE THREAD

**Issue by eyusim** [awslabs/amazon-kinesis-client#63]
After a shard split, when our original shard is being shutdown we call:

```
shutdownInput.getCheckpointer.checkpoint()
```

but we're noticing that the sequenceNumberAtShardEnd variable is being set to SHARD_END by the ShutdownTask. This causes the checkpoint in our shutdown to fail setting the lastCheckpointValue because of the following logic in RecordProcessorCheckpointer.advancePosition.

```
    if (sequenceNumberAtShardEnd != null && sequenceNumberAtShardEnd.equals(extendedSequenceNumber)) {
        // If we are about to checkpoint the very last sequence number for this shard, we might as well
        // just checkpoint at SHARD_END
        checkpointToRecord = ExtendedSequenceNumber.SHARD_END;
    }
```

since sequenceNumberAtShardEnd is "SHARD_END" and extendedSequenceNumber is an actual sequence number. 

We're using kcl version 1.6.2 and aws sdk 1.10.61. 

Are we missing a step somewhere or is this a bug in the kcl code?

Thanks,
Eugene

**Comment by pfifer** [comment]
This feature was added as part of [v1.7.1](https://github.com/awslabs/amazon-kinesis-client/releases/tag/v1.7.1).
