### ISSUE TITLE
Missing maven versions on the 1.x stream

### ISSUE THREAD

**Issue by markwoodhall** [awslabs/amazon-kinesis-client#631]
As of a few hours ago we cannot resolve versions from maven other than the latest. 

I am not a maven expert but it looks to me like the versions are all still there (https://repo1.maven.org/maven2/com/amazonaws/amazon-kinesis-client/) but the maven-metadata.xml (https://repo1.maven.org/maven2/com/amazonaws/amazon-kinesis-client/maven-metadata.xml) now only lists `1.12.0` as an available version.

Is this to be expected?

**Comment by puredanger** [comment]
I think this is a Maven central indexing problem. I filed at ticket at https://issues.sonatype.org/browse/MVNCENTRAL-5283

**Comment by markwoodhall** [comment]
> I think this is a Maven central indexing problem. I filed at ticket at [issues.sonatype.org/browse/MVNCENTRAL-5283](https://issues.sonatype.org/browse/MVNCENTRAL-5283)

Looks this is is resolved now, presume it was an indexing problem but I don't have a sonatype account to check.

**Comment by puredanger** [comment]
Yes, they reindexed over the weekend and it's fixed now.
