### ISSUE TITLE
Question: Kafka Streams API for Kafka, what is the equivalent stateful stream-processing library for Kinesis Data Streams?

### ISSUE THREAD

**Issue by nemalipuri** [awslabs/amazon-kinesis-client#641]
Sorry if this is a wrong place to ask this question.

Is there a stream-processing API for Kinesis? (like, Kafka Streams API for Kafka). I think KCL doesn't fit for this need.

To give some context on where we are coming from:

We're planning to migrate a Kafka consumer on-prom microservice to AWS platform but instead of Kafka want to use Kinesis Data Streams there.
Existing on-prem microservice uses Kafka Streams API(high-level DSL of Kafka Streams like ‘map’, ‘process’, ‘transform’, ‘join’) for aggregation, for other processing and then post messages to external REST services.

To re-write this microservice with Kinesis DS as the data streaming platform what is the best replacement for Kafka Streams? 
**Kafka Streams provides features such as event-time processing with windowing, joins, aggregations, and etc.**

Is Spark Streaming could be a fit? I'm thinking of use EMR with Spark(with Spark Streaming API) cluster for subscribing the events from Kafka DS and aggregate, window messages and then post data to external REST services.

**Or, is there a better approach that you suggest, please?**

Thanks!

**Comment by dannycranmer** [comment]
@nemalipuri AWS provide [Kinesis Data Analytics](https://aws.amazon.com/kinesis/data-analytics/) which offers fully managed stream processing using SQL or Java. The Java offering allows you to simply upload a [Flink](https://flink.apache.org/) stream processing application to a managed service with all the usual security, monitoring, scalability (etc) benefits.
