### ISSUE TITLE
PERIODIC ShardSyncStrategyType high rate of API calls

### ISSUE THREAD

**Issue by MarekMalevic** [awslabs/amazon-kinesis-client#645]
Hello,

2 weeks ago we switched to 1.12.0 and enabled PERIODIC shard sync strategy. Today I have found out that since that time DescribeStream increased significantly (50k per hour in total while previously it was way less).

I am looking to the source and cannot find a way to configure some period interval between sync calls. Is there a way of tuning periodic shard sync?

**Comment by MihirLimbachia** [comment]
I am looking to the source and cannot find a way to configure some period interval between sync calls. Is there a way of tuning periodic shard sync? --> not possible to configure a periodic interval. 

DescribeStream happens every minute..

**Comment by brendan-p-lynch** [comment]
You can use the [withShardSyncIntervalMillis](https://javadoc.io/static/com.amazonaws/amazon-kinesis-client/1.12.0/index.html?com/amazonaws/services/kinesis/clientlibrary/lib/worker/KinesisClientLibConfiguration.html). This will allow you to configure the amount of time between shard sync's using the PERIODIC shard sync strategy.
