### ISSUE TITLE
If the record processor takes more than 30 seconds to complete processRecords The KCL will automatically reconnect and start processing data again

### ISSUE THREAD

**Issue by jsohan** [awslabs/amazon-kinesis-client#651]
This can occur if the record processor takes more than 30 seconds to complete processRecords.  The KCL will automatically reconnect and start processing data again.  In the future we will not surface these exceptions, and just automatically reconnect.

_Originally posted by @pfifer in https://github.com/awslabs/amazon-kinesis-client/issues/399#issuecomment-422044379_

**Comment by jsohan** [comment]
@pfifer I'm working with nodejs and the processRecords collects data for an hour and then puts it into an S3 bucket. Sometimes this can take longer than 30 seconds to complete processRecords because it is uploading the data. Is there anyway to disable or make this time longer before it automatically reconnects?

**Comment by itsmesrds** [comment]
@jsohan How did you resolved this ??  im also facing the same issue.
