### ISSUE TITLE
Can`t use amazon kcl with localstack

### ISSUE THREAD

**Issue by khitsik** [awslabs/amazon-kinesis-client#652]
Trying to set up recordProcessor locally before deploying it. I use localstack to put records to a stream inside my docker container, but I can`t process these records with AWS KCL because of:

2019-11-15 14:43:31,648 [multi-lang-daemon-0000] ERROR s.a.kinesis.coordinator.Scheduler [NONE] - Caught exception when initializing LeaseCoordinator 
software.amazon.kinesis.leases.exceptions.DependencyException: software.amazon.awssdk.services.dynamodb.model.DynamoDbException: The security token included in the request is invalid. 

It sends the request to the real amazon dynamodb as I understand. But how can I link it with my local dynamodb?

**Comment by joro550** [comment]
I'm not sure this will "make it work" because I believe there are other issues with getting the KCL working with LocalStack right now. But to get the KCL to interact with your localstack there are two flags that you have to add to your kcl.properties file:

```
kinesisEndpoint = http://localhost:4568
dynamoDBEndpoint = http://localhost:4569
```

When you run the MultiLangDaemon it should now be looking at your local instance of kinesis and dynamo

**Comment by nicholasball** [comment]
This doesn't seem to resolve the issue unfortunately. Are there any other examples of getting KCL working with Localstack? I'm also getting the same security token error.

**Comment by upanshu21** [comment]
> This doesn't seem to resolve the issue unfortunately. Are there any other examples of getting KCL working with Localstack? I'm also getting the same security token error.

you can connect to the DynamoDB like this assuming your locakstack port is exposed on port 4566 which is the default in the localstack version.
``` public DynamoDbAsyncClient createDynamoClient(Region region) {
        return DynamoDbAsyncClient.builder().region(region)
                .credentialsProvider(() -> AwsBasicCredentials.create("test","test"))
                .endpointOverride(URI.create("http://localhost:4566"))
                .build();
    }```

```DynamoDbAsyncClient dynamoClient = createDynamoClient(region);```
