### ISSUE TITLE
Multi-Stream Support for KCL 2.x

### ISSUE THREAD

**Issue by wangajing** [awslabs/amazon-kinesis-client#655]
Hi, I was wondering if KCL 2.x has any plans to support multi streams for one application? our use case is that we publish data into different streams, and to avoid launch multiple applications, we are wondering if we can have one application that can handle the data from different streams.

**Comment by ashwing** [comment]
Yes, we are working on it. We are planning to support for only 2.X though.

**Comment by wangajing** [comment]
Thanks, glad to hear that! I saw we have a branch which already got shipped for this feature. 
 any plans for merging it into mainline? 
https://github.com/awslabs/amazon-kinesis-client/pull/691#partial-pull-merging

**Comment by swaranga** [comment]
Why not just start two instances of `software.amazon.kinesis.coordinator.Scheduler` in the same VM?You can assign two separate DDB tables for the checkpointing. We use `applicationName + "-" + streamName` for the DDB tables so there is no overlap.

**Comment by joshua-kim** [comment]
Hi, this was merged in as part of the [v2.3.0 release](https://github.com/awslabs/amazon-kinesis-client/releases/tag/v2.3.0), where it is now being supported experimentally. This is **not** forwards/backwards compatible, however the functionality is available for experimental use.
