### ISSUE TITLE
KCL 1.9.x consumer stop consuming kinesis data after resharding

### ISSUE THREAD

**Issue by cabbagebai** [awslabs/amazon-kinesis-client#662]
When we reshard our kinesis from around 400 to 300, we noticed new shards are created in the dynamodb table, but the consumer didn't process any data until we delete and recreate the dynamodb and kinesis stream.
This problem happened randomly when we do resharding, any one has met same issue before?

**Comment by ashwing** [comment]
Please upgrade to latest KCL version. We have a bug fix for that.
