### ISSUE TITLE
worker intermittently lose leases and fails checkpointing

### ISSUE THREAD

**Issue by JFen9** [awslabs/amazon-kinesis-client#677]
Every few days I'm getting `DynamoDBLeaseRenewer:317 - Worker a lost lease with key shardId-03 - discovered during update` and then a ShutdownException:`Can't update checkpoint - instance doesn't hold the lease for this shard`.

I looked through some similar issues and here are some observations:
- There are no other workers stealing leases from this worker since if so I would have seen `Worker b needed 2 leases but none were expired, so it will steal lease shardId-03 from a` in the log, but I didn't see any.
- I didn't see any logs matching `Worker a could not update lease with key shardId-03 because it does not hold it` or `Worker a refusing to update lease with key shardId-03 because concurrency tokens don't match`.
- There is a `ConditionalCheckFailedRequests` showing up on the corresponding dynamodb table, so the failure likely happened during dynamodb write.

client version: 2.2.7

Appreciate any pointers as to why the UpdateLease would fail. Thanks.

**Comment by MihirLimbachia** [comment]
Please check if there s throttling on the DDB table.

**Comment by MihirLimbachia** [comment]
what is the failoverTimeMillis in your application ? If it is by default 10s, please increase it if your to atleast twice the average processing time of your record processor as if your application checkpoints after processing and some one else got the lease, you will recieve ConditionalCheckFailedExceptions while checkpointing.

Moreover, by default leaseRenewal thread pool has a size of 20. Hence, if the worker is handling more than 20 shards and DDB update takes a few seconds, it is possible that the lease renewal fails.

Also, please check if you are being throttled on the DDB table.

Hence, you may increase the lease renewal thread pool size from the default 20. 

https://github.com/awslabs/amazon-kinesis-client/blob/8b7c1554cba79de2ae4d4fff45de23d16f2cea9e/amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/LeaseManagementConfig.java#L149

Morover, if your application is facing lot of Garbage collection, it is possible that the lease renewal threads are delayed upto the point of losing leases..However, this is not that common...
