### ISSUE TITLE
Can't setDynamoDBEndpoint from .properties

### ISSUE THREAD

**Issue by jordanhamill** [awslabs/amazon-kinesis-client#685]
I've recently just migrated to v2.0.1 of the amazon-kinesis-client-python that uses KCL 2.1.2.

We previously had a localstack setup where we set `kinesisEndpoint` and `DynamoDBEndpoint` in the `consumer.properties` file.  

```
...
kinesisEndpoint = ${LOCALSTACK_URL}:4568
DynamoDBEndpoint = ${LOCALSTACK_URL}:4569
MetricsLevel = None
```
```
/usr/bin/java -cp \
  $VIRTUAL_ENV/lib/python3.6/site-packages/amazon_kclpy/jars/*:/app/consumer \
  software.amazon.kinesis.multilang.MultiLangDaemon \
  --properties-file consumer.properties
```

It doesn't look like these are being used anymore as I'm seeing the following logs start up:
> [multi-lang-daemon-0000] INFO  s.a.kinesis.coordinator.Scheduler [NONE] - Initialization attempt 1
> [multi-lang-daemon-0000] INFO  s.a.kinesis.coordinator.Scheduler [NONE] - Initializing LeaseCoordinator
> [multi-lang-daemon-0000] ERROR s.a.k.l.d.DynamoDBLeaseRefresher [NONE] - Failed to get table status for test-consumer
> software.amazon.kinesis.leases.exceptions.DependencyException: software.amazon.awssdk.services.dynamodb.model.DynamoDbException: The security token included in the request is invalid. (Service: DynamoDb, Status Code: 400, ...
> at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseRefresher.tableStatus(DynamoDBLeaseRefresher.java:181)
> at software.amazon.kinesis.leases.dynamodb.DynamoDBLeaseRefresher.createLeaseTableIfNotExists(DynamoDBLeaseRefresher.java:115)

I'm not a java dev but I had a small look around `MultiLangDaemonConfiguration` and `MultiLangDaemonConfig`, I can't see a path for the properties config calling `setDynamoDBEndpoint`.

It also looks like `KinesisClientLibConfiguration` is no longer used and the only references are in outdated comments.

Are these properties no longer settable?  

*note: I am aware there are other issues with Enhanced Fan Out and localstack but as well but this seems unrelated*

**Comment by jordanhamill** [comment]
I changed the case of `DynamoDBEndpoint` to `dynamoDBEndpoint` and it set the endpoint correctly.

**Comment by MrAfrazKhan** [comment]
Hi, I am trying to implement kcl for ddb streams, @jordanhamill can you tell me how to set the above configurations as you told? cz i can't see any consumer.properties file in repo or if I have to make it from scratch. Please guide.

**Comment by jordanhamill** [comment]
@MrAfrazKhan I haven't used the KCL quite a while now but this is the template I had for running various python applications on ECS and using [localstack](https://github.com/localstack/localstack). Hopefully it helps.

```
executableName = poetry run python -m consumer

streamName = ${stream_name}

# Disable enhanced fan out
retrievalMode = POLLING
applicationName = ${application_name}

AWSCredentialsProvider = DefaultAWSCredentialsProviderChain

processingLanguage = python/3.6

initialPositionInStream = TRIM_HORIZON

# The KCL defaults to us-east-1
regionName = us-east-1

% if kinesis_endpoint:
kinesisEndpoint = ${kinesis_endpoint}
% endif

# DynamoDB endpoint
% if dynamo_endpoint:
DynamoDBEndpoint = ${dynamo_endpoint}
% endif

% if metrics_level:
MetricsLevel = ${metrics_level}
% endif

callProcessRecordsEvenForEmptyRecordList = true
```

You can do something like this

```sh
poetry run mako-render \
           --var application_name=$APPLICATION_NAME \
           --var kinesis_endpoint="${LOCALSTACK_URL}:4568" \
           --var dynamo_endpoint="${LOCALSTACK_URL}:4569" \
           --var metrics_level="None" \
           consumer/properties.template > $PROPERTIES_FILE_PATH
```

**Comment by MrAfrazKhan** [comment]
@jordanhamill thanks for the quick response, let me do this way.
