### ISSUE TITLE
IRecordProcessor.initialize() needs checkpoint sequence number

### ISSUE THREAD

**Issue by llamahunter** [awslabs/amazon-kinesis-client#7]
If restarting from beyond the 24 hour window of the Kinesis stream, the record processor may need to read from some other backing store (S3/DynamoDB/etc) to catch up to the Kinesis stream.  To do so, it needs to know when the last checkpoint was.  This is clearly available a couple of lines above in InitializeTask.java.  Please pass through to record processor so that it can prepare itself to go when processRecords() is first called.

**Comment by superlogical** [comment]
@llamahunter Did you bother with Amazon Kinesis? Seems like you ran into a few problems, with not much luck?

**Comment by llamahunter** [comment]
I am using KCL, with a number of personal modifications (passing checkpoint position on startup, a catchup phase before starting shard consumption, delays before consuming stolen shards, etc).  Still, it's a bit of a pain to use, especially because the shard handoff between workers is so haphazardly done. There are other issues with Kinesis, tho, so my company is planning to switch to Kafka.

**Comment by rnienhuis** [comment]
Hi @llamahunter -  I work for the Amazon Kinesis team. 

Sorry that the features you need are not available in the KCL. Any other feedback you provide on the issues you mention above would be greatly appreciated.

**Comment by mchv** [comment]
I think this issue could be closed as now `InitialisationInput` [contains the checkpoint sequence number](https://github.com/awslabs/amazon-kinesis-client/blob/master/src/main/java/com/amazonaws/services/kinesis/clientlibrary/types/InitializationInput.java#L59)
