### ISSUE TITLE
Handling issues with records after KCL delivered it to consumer

### ISSUE THREAD

**Issue by v9ru** [awslabs/amazon-kinesis-client#702]
I have a Kinesis stream consumer using KCL. 
What will happen in the following case?
1. KCL delivered a few records and we faced issues with those records and don't want to checkpoint those.
2. Now new records are added to the stream

Will KCL deliver the new records? or will it try to re-deliver the old records after sometime?

Ideally, I would like to get old records again. (So that I can push a fix if needed to handle those)

But I am not seeing that behaviour. I am getting new records and my application is checkpoint those and hence I am losing the old records.

If there are no new records added to the stream and if I kill and restart my consumer I am getting the old records again. How can I do this without killing my consumer

Note: I am using spring-cloud-stream-binder-kinesis with kcl enabled

**Comment by Cory-Bradshaw** [comment]
Hello,

Kinesis, and stream processing in general, checkpoints based on sequences of records to fallback to that sequence that was last checkpointed by the KCL when it needs to restart for any number of reasons.  These checkpoints are not a record "ACK" like you see in Queue processing. If you decide to skip a record, the stream will continue processing likely never coming back to that record again without intervention.

What is the goal you are trying to achieve by not checkpointing the records you don't want to process? Is it an ordering problem you are trying to solve by not processing the records the KCL delivers?
