### ISSUE TITLE
Parallel lease stealing

### ISSUE THREAD

**Issue by gpereraDX** [awslabs/amazon-kinesis-client#708]
### CONTEXT
There are 40 shards and 5 KCL workers (so each have 8 shards). When I start a 6th KCL worker, this worker starts stealing shards from the already running KCL workers. But this 6th worker steals shards every 6 min, and one shard per other worker. My KCL configuration overrides the max leases to steal at one time to 5. But from reading logs of the LeaseCoordinator, it seems to be max leases to steal per worker.

### QUESTION
Is it possible to allow a new KCL worker to steal shards from multiple other workers in the same LeaseCoordinator iteration of shard rebalancing?

**Comment by joshua-kim** [comment]
You can configure how many leases to steal via `LeaseManagementConfig#maxLeasesToStealAtOneTime`, but this currently only supports stealing from the worker that's holding the most leases for shard load rebalancing. You can increase this to allow for faster load distribution if this helps your use case, but currently KCL does not support stealing from multiple workers simultaneously.
