### ISSUE TITLE
KCL 2.x RecordAdapter Equivalent

### ISSUE THREAD

**Issue by bpaw** [awslabs/amazon-kinesis-client#714]
Hello, I am trying to migrate a project from 1.9 to 2.2.10, but I am running into an issue in regards to not being able to use `com.amazonaws.services.dynamodbv2.streamsadapter.model.RecordAdapter`. The KCL 2.2.10 seems to be forcing me to implement `processRecords` to take in a KinesisClientRecord object, which is not compatible with the above RecordAdapter. I was wondering if there is an equivalent way for me to get the DynamoDb record? I need access to the `getNewImage()` and `getOldImage()` and `getEventName()` in order for this migration from 1.9 to 2.2 to be successful.

**Comment by ashwing** [comment]
Hello, this should be a request to DDB streams team.
