### ISSUE TITLE
0 records sent successfully to destinations (wrong destination)

### ISSUE THREAD

**Issue by bgdnlp** [awslabs/amazon-kinesis-client#72]
There was another issue open about a similar issue.

The agent doesn't produce an error if it's given the wrong stream, it just says something like:
```Progress: X records parsed (X bytes), and 0 records sent successfully to destinations. Uptime: Xms```
In my case the issue was that I had ```kinesisStream``` in the config file (I just edited the default config, didn't pay enough attention) instead of ```deliveryStream```, for Firehose. At least I'm not the only one: https://forums.aws.amazon.com/message.jspa?messageID=679124

Is it possible to have an error in logs in such cases, instead of (almost) silently failing?

I have rpm version "1.1-1.amzn1", installed by running yum install on an Amazon Linux instance.

**Comment by pfifer** [comment]
This issues appears to be for the [amazon-kinesis-agent](https://github.com/awslabs/amazon-kinesis-agent), and not the amazon-kinesis-client.  You will want to [create an issue in that project](https://github.com/awslabs/amazon-kinesis-agent/issues).
