### ISSUE TITLE
What's the benefit of migration from v1 to v2?

### ISSUE THREAD

**Issue by yxiehbo** [awslabs/amazon-kinesis-client#733]
Is there a document explaining why we should migrate from v1 to v2?

**Comment by priyath** [comment]
Interested in this as well. Currently about to write a consumer and wondering whether to go with 1.x or 2.x

**Comment by fahadhasher** [comment]
> Interested in this as well. Currently about to write a consumer and wondering whether to go with 1.x or 2.x

@priyath I believe the biggest difference between the two is the support for mighty `Enhanced-fanout Consumer` that enables you to fetch records from a stream with dedicated throughput of up to 2 MB/s per shard, of course that'll incur an extra cost as well. You can go through the following [release notes](https://github.com/awslabs/amazon-kinesis-client/releases/tag/v2.0.0) and some documentation around [enhanced fanout consumer](https://docs.aws.amazon.com/streams/latest/dev/building-enhanced-consumers-api.html).
Thanks!

**Comment by brendan-p-lynch** [comment]
Here is additional documentation to look at from aws: https://docs.aws.amazon.com/streams/latest/dev/kcl-migration.html.
