### ISSUE TITLE
How to decode a sequence number?

### ISSUE THREAD

**Issue by leosurwiki** [awslabs/amazon-kinesis-client#738]
I want to get the approximate arrival time from the sequence number, and did some reverse engineering:
I can confirm that (sequence_number >> 4) & ((1 << 32) - 1) is the shard id.
And I tried to publish 5 events, and increase the interval linearly for 30 to 120 second.
For (sequence_number >> 36) & ((1 << 32) - 1),  they are [1599865913, 1599865943, 1599866003, 1599866094, 1599866214], and I assume they are probably approximate arrival time(unit is second).
For (sequence_number >> 68) & ((1 << 64) - 1), they are [34710911000576, 34710953291776, 34711039733760, 34711165267968, 34711339130880], which is also proportional to when the event is published.

Are there any documentation about how to decode a sequence number?

**Comment by joshua-kim** [comment]
There isn't any documentation on how to do this, sequence numbers are generated on the Kinesis side using some metadata (timestamp, some internal Kinesis stuff, etc) and encoding them. It would probably be simpler to use the [ApproximateArrivalTimestamp](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_Record.html#Streams-Type-Record-ApproximateArrivalTimestamp) that comes from the GetRecords response if your use-case is to figure out when a record arrived at the service.
