### ISSUE TITLE
Kinesis Client library 1.6.3 (latest) does not work with AWS Java SDK 1.11.x (latest)

### ISSUE THREAD

**Issue by smurty** [awslabs/amazon-kinesis-client#74]
KCL still depends on JSONObject (in package com.amazonaws.util.json) which as per AWS 1.11 release notes has been removed in favor of the Jackson Json library.
So, is there a KCL in the works (and what is the availability date?) that would allow us to upgrade to AWS 1.11.x ?

**Comment by nathgs** [comment]
I've had a crack at this and got KCL working with AWS SDK 1.11.x. Have a look at my pull request #75 if you are interested.

**Comment by smurty** [comment]
Thanks Nathan !

I did something similar for one of our internal projects that used AWS's JSONObject & JSONArray but I was not sure how AWS would upgrade KCL.

So I held off, but thanks for your help.


________________________________

**Comment by sihil** [comment]
This has impacted us too. I've raised an AWS support case.

**Comment by smurty** [comment]
Great thanks ! Appreciate if you could post if/when you hear back from AWS.

**Comment by pfifer** [comment]
I'm currently in the process of updating the KCL to AWS SDK 1.11.  I'm currently testing the SDK 1.11 change, and a couple other PR's.  I'm hoping to have a release ready, and out in the next two weeks.

**Comment by rdifalco** [comment]
KCL not working with 1.11.X is hurting us. Any idea when a new release will be made?

**Comment by pfifer** [comment]
The KCL has been updated to AWS Java SDK 1.11.  The artifacts are being release in Maven right now.

Sorry for the delay.
