### ISSUE TITLE
Incorrectly replaying all the records from TRIM_HORIZON if lease lost after resharding

### ISSUE THREAD

**Issue by aloysiustany** [awslabs/amazon-kinesis-client#751]
I have my KCL app deployed in AWS ECS. I do not have any manual checkpointing in the `processRecords` method
Hence after resharding, the child shards will have a checkpoint TRIM_HORIZON in dynamodb table. And it will stay as TRIM_HORIZON forever. 
Now, if I add an additional instance of my KCL app, then the shards will get shared.
Since the checkpoint is TRIM_HORIZON, the shards which moved to the new instance will start reading from TRIM_HORIZON instead of continuing where the older instance left. 

KCL version used: 2.3.1

**Comment by ashwing** [comment]
Without checkpointing the application will never know where to resume. You at least need to checkpoint on shard end for the children shards to be picked up

**Comment by aloysiustany** [comment]
I am checkpointing at shard end. But, the problem is child shards are having TRIM HORIZON. Is it possible to set the check point to LATEST for any new child shards?

**Comment by ashwing** [comment]
The child shards' TRIM_HORIZON points to the time these shards were created
and not that of the stream. You would want your child shards to read from
this time to avoid any data loss. For instance, if it takes 30 seconds to
start processing your child shard, setting to LATEST would loose that 30
seconds of data. Setting to TRIM_HORIZON would read from 30 seconds ago.
