### ISSUE TITLE
Recurring warning - unable to clean up lease on KCL 2.3

### ISSUE THREAD

**Issue by priyath** [awslabs/amazon-kinesis-client#752]
I performed a re-sharding from 1 shard to 2 after which my KCL consumer keeps logging the following warning every one minute.

` Unable to clean up lease shardId-000000000006 for newStream due to LeaseCleanupManager.LeaseCleanupResult(cleanedUpCompletedLease=false, cleanedUpGarbageLease=false, wereChildShardsPresent=true, wasResourceNotFound=false)`

shardId-000000000006 is the parent shard that was split into two child shards 7 and 8. My DynamoDB entries are like so:
![Screenshot from 2020-11-07 09-39-50](https://user-images.githubusercontent.com/10166923/98431682-997e8900-20dd-11eb-95cb-fe58bc99f6db.png)

A restart of the consumer does not help. Is this a cause for concern, and why is the worker unable to clean up the lease on shardId-000000000006?

**Comment by priyath** [comment]
Once both the child shards performed the checkpointing, shardId-000000000006 lease was cleaned up. I guess that is the expected behavior.

**Comment by adrian-skybaker** [comment]
>I guess that is the expected behavior.

In that case, why is it logged at WARN level? Should this be corrected?
