### ISSUE TITLE
Constantly getting this error: Cancelling subscription, and restarting. Last successful request details -- request id - NONE, timestamp - NONE**

### ISSUE THREAD

**Issue by emosqueda** [awslabs/amazon-kinesis-client#757]
Hi, I am getting this error each minute or even less after I migrated some consumers from KCL 1.x to KCL 2.3.1:

**shardId-001: Last request was dispatched at 2020-11-26T18:24:58.616878Z, but no response as of 2020-11-26T18:25:58.626413Z.  Cancelling subscription, and restarting. Last successful request details -- request id - NONE, timestamp - NONE**

Is this something that I should be worried about - what might be causing this?

**Comment by ashwing** [comment]
Can you share more logs? Is your application processing records?
