### ISSUE TITLE
Incomplete hash range found between when use DynamoDB Stream Adapter

### ISSUE THREAD

**Issue by xinatcg** [awslabs/amazon-kinesis-client#758]
version: 1.14.0

error:

```
Incomplete hash range found between 
```

someone other gets the same error: https://stackoverflow.com/questions/64231432/dynamodb-stream-kinesis-incomplete-hash-range-found-between/65029807#65029807

related code: 

https://github.com/awslabs/amazon-kinesis-client/blob/6fbfc21ad7d6a2722491806a411d168304167f7f/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/PeriodicShardSyncManager.java#L298-L301

the table `endingHashKey` in the dynamodb is 1, so this check equal to MAX_HASH_KEY, so always get this error  when check the range.

**Comment by ashwing** [comment]
KCL 1.14.X is not compatible to Dynamodb streams adapter. Please reach out to streams adapter owners to check when it will be made compatible.
