### ISSUE TITLE
Set log level from command line

### ISSUE THREAD

**Issue by callumj** [awslabs/amazon-kinesis-client#76]
Is it possible to add documentation on how to set the log level of the Consumer? We'd like to log WARN and higher, we find that INFO is too verbose for us.

**Comment by geoah** [comment]
Very interested in this as well. tried `log4j.rootLogger=WARN` that the Amazon SDK is using but didn't seem to work for KCL.
Any other suggestions?

**Comment by pfifer** [comment]
The KCL uses [Apache Commons Logging](https://commons.apache.org/proper/commons-logging/) to log messages.  The KCL, and none of it's runtime dependencies, actually bring in a logging platform.  With no additional logging platform Commons Logging defaults to [SimpleLog](http://commons.apache.org/proper/commons-logging/apidocs/org/apache/commons/logging/impl/SimpleLog.html), which does appear to support some configuration properties.  Specifically `org.apache.commons.logging.simplelog.defaultlog`, which controls the log level.

I would recommend choosing a log system, and initializing it normally though.  SimpleLog just outputs everything to standard error.

**Comment by zeynepsu** [comment]
Adding this to our internal backlog to track. Closing this issue.
