### ISSUE TITLE
add support for web identity token credentials

### ISSUE THREAD

**Issue by vicki-c** [awslabs/amazon-kinesis-client#761]
I'm trying to run the Kinesis Python client on EKS, where the credentialing mechanism is web identity token. However, when I set the credential provider to the default chain like so:

```
AWSCredentialsProvider = DefaultAWSCredentialsProviderChain
```

the workers seem to attempt to use the instance profile to access AWS APIs instead, based on the request logs.

I have confirmed that the IAM policies are set up correctly. When I manually set the access key credentials in the environment (via `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`), the workers work correctly.

I believe a couple of things need to happen in order to support web identity tokens:

1. The AWS Java SDK version used in `multilang` needs to be bumped from `1.11.477` to at least `1.11.704`, based on [the documentation](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html). 
2. The `aws-java-sdk-sts` module needs to be added as a dependency, based on the debug log:

```
[DEBUG] AWSCredentialsProviderChain - Unable to load credentials from WebIdentityTokenCredentialsProvider: To use assume role profiles the aws-java-sdk-sts module must be on the class path.
```

**Comment by yogesh8177** [comment]
Facing the same issue. Any update on this issue?

**Comment by vicki-c** [comment]
I think we're waiting for AWS to merge the linked PRs. :(

**Comment by vicki-c** [comment]
The PRs were merged
