### ISSUE TITLE
KCL 1.14.0 can corrupt checkpoint tables if multiple streams are processed on the same JVM

### ISSUE THREAD

**Issue by dbottini** [awslabs/amazon-kinesis-client#764]
Hello,

We run a service that processes two different streams on the same node using two separate instances of `Worker`. We had an issue where when we re-sharded one of the two streams, processing on the OTHER stream would reset to TRIM_HORIZON and process all the way from the oldest record. The problem here is that the new `LeaseCleanupManager` uses a singleton configured with a single `LeaseManager`, which is hardwired to a single Kinesis stream. When either stream reaches the end of shard X, it'll add that shardId onto the `LeaseCleanupManager`. Eventually, `LeaseCleanupManager` will take that `shardId` and delete that lease from the checkpoint table for the stream whose `Worker` was initialized first. 

Thus, this bug requires three conditions to be true to corrupt the checkpoint table by deleting the wrong checkpoints:
1. Two streams are processed on the same JVM
2. The two streams have overlapping `shardId` values
3. The latter of the two streams re-shards

(Also, a nit: `LeaseCleanupManager`'s singleton instantiation is not thread-safe - if we created our `Worker` in parallel we could instantiate two different instances and nondeterministically have one set for use by later calls to `LeaseCleanupManager.createOrGetInstance`)

Edit: reflected that the single `LeaseManager` is the thing that most causes this issue, not `KinesisProxy`

**Comment by ashwing** [comment]
Are you having same ddb lease table for both the streams? If yes then you
will have overlapped values from both the applications. Otherwise both the
applications would not and should not interfere.

**Comment by dbottini** [comment]
We have different DynamoDB tables, yes.

Ideally, they shouldn't interfere, but due to the shared singleton of `LeaseCleanupManager` and its instance variable `LeaseManager` that hooks up to a single table, `LeaseCleanupManager` will only interact with that one table. (My original comment attributed the error due to a shared `KinesisProxy`, but it is actually the `LeaseManager` that interacts with the actual table. Although, the shared `KinesisProxy` would fail to return child shards correctly, as it only queries the stream for which the `KinesisProxy` was instantiated.

**Comment by ashwing** [comment]
I see. Ya in a single JVM this can happen. PR is appreciated. Otherwise
will check with the team on priority.

**Comment by ashwing** [comment]
Rolling out a fix in 1.14.1

**Comment by ashwing** [comment]
Fixed in 1.14.1
