### ISSUE TITLE
Update MultiLangDemon to support 1.3+ versions

### ISSUE THREAD

**Issue by a8m** [awslabs/amazon-kinesis-client#77]
There are two critical features that are missing for those who work with the KPL
- UserRecord's fields are missing. for example '[subSequenceNumber](https://github.com/awslabs/amazon-kinesis-client/blob/master/src/main/java/com/amazonaws/services/kinesis/clientlibrary/types/UserRecord.java#L46)'
- The ability to specify the subsequence number at which to [checkpoint](https://github.com/awslabs/amazon-kinesis-client/blob/master/src/main/java/com/amazonaws/services/kinesis/multilang/MultiLangProtocol.java#L198)

Thanks

**Comment by kerbelp** [comment]
Any update on this issue?

**Comment by pfifer** [comment]
I'm in the process of updating the MultiLangDaemon to the newer version of the KCL, but that update won't include these features.  I'm going to place adding these features on our backlog, and begin prioritizing them.  There is a lot of desire to add these features so I'll be making sure they are a higher priority.

**Comment by jdnurmi** [comment]
As long as we're asking, can I ask for 1.4+? (Dis)Aggregation support via the MLD would be a game changer for some of our performance constraints.

**Comment by pfifer** [comment]
The Python client has been updated to add these features, but I haven't had a chance to do the other clients.  I don't have an ETA of when we will have those updated at this time.

@jdnurmi All of the clients now support are using 1.7.0 or newer of the Kinesis Client Library.  They should now all support reading data sent by the Kinesis Producer Library.

**Comment by pfifer** [comment]
Created issues in the other clients for updating their feature sets.

Closing this in favor of tracking those issues.
