### ISSUE TITLE
Workers not started with KCL 1.6.3

### ISSUE THREAD

**Issue by david-mcneil** [awslabs/amazon-kinesis-client#80]
We tried upgrading an app from KCL 1.6.1. to 1.6.3 and found that the application no longer reliably started workers. It would seem to obtain leases, but records were never retrieved. We reverted to KCL 1.6.1 and the problem went away.

**Comment by pfifer** [comment]
I didn't see anything like this while I was testing the 1.6.4 version.  Can you try the new version, and see if it helps.

If you see it happen again any log data, or repro you could provide would be helpful.

Thanks

**Comment by david-mcneil** [comment]
I will plan on giving 1.6.4 a try. Thanks.

**Comment by david-mcneil** [comment]
The same problem occurred with 1.6.4. Presumably it is something particular about the way we are using the KCL, but I don't have any ideas offhand of what that might be. Unfortunately I am not in a position to debug it at the moment.

**Comment by david-mcneil** [comment]
Here is the KCL log messages when it fails to start processing events. This is running on com.amazonaws/aws-java-sdk "1.11.14" and com.amazonaws/amazon-kinesis-client "1.6.4" :

`DEBUG 2016-07-19 15:01:44,559+0000 [main] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: The region of Amazon CloudWatch client has been set to us-west-2
DEBUG 2016-07-19 15:01:44,575+0000 [main] com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy: KinesisProxy( app1)
DEBUG 2016-07-19 15:01:44,587+0000 [main] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: The region of Amazon Kinesis client has been set to us-west-2
DEBUG 2016-07-19 15:01:44,587+0000 [main] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: The region of Amazon DynamoDB client has been set to us-west-2
INFO  2016-07-19 15:01:44,590+0000 [pool-0] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Initialization attempt 1
INFO  2016-07-19 15:01:44,590+0000 [pool-0] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Initializing LeaseCoordinator
INFO  2016-07-19 15:01:44,690+0000 [pool-0] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Syncing Kinesis shard info
INFO  2016-07-19 15:01:44,707+0000 [main] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Worker shutdown requested.
DEBUG 2016-07-19 15:01:44,846+0000 [pool-0] com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer: Num shards: 1
DEBUG 2016-07-19 15:01:44,937+0000 [pool-0] com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer: Existing lease: {
  "leaseKey" : "shardId-000000000000",
  "leaseOwner" : "02ef6cf0-f766-47d5-af78-6a0fbf7e87eb",
  "leaseCounter" : 2660988,
  "concurrencyToken" : null,
  "lastCounterIncrementNanos" : null,
  "checkpoint" : {
    "sequenceNumber" : "49563941839802648629865244901440221832044759084882198530",
    "subSequenceNumber" : 0
  },
  "ownerSwitchesSinceCheckpoint" : 3,
  "parentShardIds" : [ ]
}
DEBUG 2016-07-19 15:01:44,937+0000 [pool-0] com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer: Found open shard: shardId-000000000000
DEBUG 2016-07-19 15:01:44,937+0000 [pool-0] com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer: Evaluating leases for open shard shardId-000000000000 and its ancestors.
DEBUG 2016-07-19 15:01:44,937+0000 [pool-0] com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer: Lease for shardId shardId-000000000000 already exists. Not creating a lease
DEBUG 2016-07-19 15:01:44,938+0000 [pool-0] com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer: Num new leases to create: 0
INFO  2016-07-19 15:01:44,940+0000 [pool-0] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Starting LeaseCoordinator
DEBUG 2016-07-19 15:01:47,107+0000 [main] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: The region of Amazon CloudWatch client has been set to us-west-2
DEBUG 2016-07-19 15:01:47,115+0000 [main] com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy: KinesisProxy( app1)
DEBUG 2016-07-19 15:01:47,116+0000 [main] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: The region of Amazon Kinesis client has been set to us-west-2
DEBUG 2016-07-19 15:01:47,116+0000 [main] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: The region of Amazon DynamoDB client has been set to us-west-2
INFO  2016-07-19 15:01:47,116+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Initialization attempt 1
INFO  2016-07-19 15:01:47,116+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Initializing LeaseCoordinator
INFO  2016-07-19 15:01:47,160+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Syncing Kinesis shard info
DEBUG 2016-07-19 15:01:47,288+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer: Num shards: 1
DEBUG 2016-07-19 15:01:47,297+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer: Existing lease: {
  "leaseKey" : "shardId-000000000000",
  "leaseOwner" : "02ef6cf0-f766-47d5-af78-6a0fbf7e87eb",
  "leaseCounter" : 2660988,
  "concurrencyToken" : null,
  "lastCounterIncrementNanos" : null,
  "checkpoint" : {
    "sequenceNumber" : "49563941839802648629865244901440221832044759084882198530",
    "subSequenceNumber" : 0
  },
  "ownerSwitchesSinceCheckpoint" : 3,
  "parentShardIds" : [ ]
}
DEBUG 2016-07-19 15:01:47,297+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer: Found open shard: shardId-000000000000
DEBUG 2016-07-19 15:01:47,297+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer: Evaluating leases for open shard shardId-000000000000 and its ancestors.
DEBUG 2016-07-19 15:01:47,297+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer: Lease for shardId shardId-000000000000 already exists. Not creating a lease
DEBUG 2016-07-19 15:01:47,297+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer: Num new leases to create: 0
INFO  2016-07-19 15:01:47,297+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Starting LeaseCoordinator
INFO  2016-07-19 15:01:54,964+0000 [pool-0] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Initialization complete. Starting worker loop.
INFO  2016-07-19 15:01:54,965+0000 [pool-0] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: All record processors have been shutdown successfully.
INFO  2016-07-19 15:01:54,965+0000 [pool-0] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Starting worker's final shutdown.
INFO  2016-07-19 15:01:54,965+0000 [pool-0] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Worker loop is complete. Exiting from worker.
INFO  2016-07-19 15:01:57,309+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Initialization complete. Starting worker loop.
INFO  2016-07-19 15:02:47,537+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: No activities assigned
INFO  2016-07-19 15:02:47,538+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Sleeping ...
INFO  2016-07-19 15:03:48,337+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: No activities assigned
INFO  2016-07-19 15:03:48,337+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Sleeping ...
INFO  2016-07-19 15:04:49,136+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: No activities assigned
INFO  2016-07-19 15:04:49,136+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Sleeping ...
INFO  2016-07-19 15:05:49,576+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: No activities assigned
INFO  2016-07-19 15:05:49,576+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Sleeping ...
INFO  2016-07-19 15:06:50,372+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: No activities assigned
INFO  2016-07-19 15:06:50,372+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Sleeping ...
INFO  2016-07-19 15:07:51,169+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: No activities assigned
INFO  2016-07-19 15:07:51,169+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Sleeping ...
INFO  2016-07-19 15:08:51,966+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: No activities assigned
INFO  2016-07-19 15:08:51,966+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Sleeping ...
INFO  2016-07-19 15:09:52,769+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: No activities assigned
INFO  2016-07-19 15:09:52,770+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Sleeping ...
INFO  2016-07-19 15:10:53,567+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: No activities assigned
INFO  2016-07-19 15:10:53,567+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Sleeping ...
INFO  2016-07-19 15:11:54,364+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: No activities assigned
INFO  2016-07-19 15:11:54,365+0000 [pool-1] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Sleeping ...
`

**Comment by pfifer** [comment]
Somewhere something is calling `Worker#shutdown()`.
```
INFO 2016-07-19 15:01:44,707+0000 [main] com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker: Worker shutdown requested.
```
This causes the lease coordinator to stop, which will prevent record processors from being started.

**Comment by david-mcneil** [comment]
Thank you! I will pursue that lead to find what is going wrong.

**Comment by david-mcneil** [comment]
For esoteric reasons our application was starting a worker, shutting it down, then starting it again. Would you expect this to have the net effect of leaving it shutdown?

**Comment by pfifer** [comment]
Was your application recreating the Worker, or reusing the shutdown Worker?

**Comment by david-mcneil** [comment]
I believe it was recreating the Worker, but I need to verify.

**Comment by david-mcneil** [comment]
Yes, the app created a new Worker. From studying the logs it seems Worker 1 was shutting down at the same time that Worker 2 was starting. Where both Worker 1 and Worker 2 were workers for the same app. Possibly this is not a supported usage pattern?

**Comment by pfifer** [comment]
I don't believe the worker uses any global state, but I could be wrong.  This is something I've never tested for.  For most of the Kinesis applications I've seen the worker shutting down is usually followed by the process exiting.

**Comment by pfifer** [comment]
Did the two workers use the same worker id value?  I'm not sure how the lease management would react to that.  

I haven't had a chance to test this case yet.

**Comment by david-mcneil** [comment]
I don't have the answer to that question ready at hand, sorry. If I have a chance to track that down I will plan on posting the answer here.

Thanks.
