### ISSUE TITLE
can we sent the data streams to private URL by using kinesis delivery streams.

### ISSUE THREAD

**Issue by manavalan619** [awslabs/amazon-kinesis-client#826]
Amazon Kinesis Data Firehose can we send the data streams to custom HTTP endpoint or HTTP endpoints which is private URL. Let assume my application is deployed on AWS ECS and  I configure application load balancer as internal load balancers and set the target group for the deployed application on AWS ECS which means it only works as within VPC. 

Is there possible to send the data streams to the Internal load balancer. or any other approach for this.

**Comment by zeynepsu** [comment]
Thank you for logging this issue. Please use the cloud support feature since your issue is pertaining to the Firehose service. Closing this issue.
