### ISSUE TITLE
Client initialization failed

### ISSUE THREAD

**Issue by Ing-zx** [awslabs/amazon-kinesis-client#830]
Kinesis error log:
Curl perform failed for url https://c1ybkrkbr1j10x.credentials.iot.us-west-2.amazonaws.com/role-aliases/alias_iam_wyze_kvs_role/credentials with result Timeout was reached : Operation timed out after 0 milliseconds with 0 out of 0 bytes received

libcurl version : 7.36.0

The return value of the function “ createDefaultCallbacksProviderWithIotCertificate”  is 0x1500 0011

I use the same iot certificate, but often fail to initialize

**Comment by brendan-p-lynch** [comment]
Closing as this does not look like it is related to KCL. Please provide more information and re-open if you expect it is.
