### ISSUE TITLE
Warning always logged when deleting stale streams

### ISSUE THREAD

**Issue by mrknmc** [awslabs/amazon-kinesis-client#832]
Even when there are no stale streams to delete, a warning is logged: https://github.com/awslabs/amazon-kinesis-client/blob/master/amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/Scheduler.java#L568-L571

This can cause a lot of noise and we don't want to completely mute the `Scheduler` logger. I can contribute a PR just let me know if you'd prefer to change the log level or avoid the log when no stale streams are found.

**Comment by brendan-p-lynch** [comment]
This should be resolved by https://github.com/awslabs/amazon-kinesis-client/blob/master/amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/Scheduler.java#L574.
