### ISSUE TITLE
please expose "ApproximateArrivalTimestamp" via JsonFriendlyRecord

### ISSUE THREAD

**Issue by zdjohn** [awslabs/amazon-kinesis-client#85]
Even though ApproximateArrivalTimestamp is becoming available in Record. However it is not exposed in JsonFriendlyRecord. 
This means "ApproximateArrivalTimestamp" is not exposed to anyone who uses KCL and use ProcessRecordsMessage to consume Kinesis Stream. (e.g. .Net developers like me)

The fix is relative simple, and I am happy to provide PR for it.

PS: https://github.com/awslabs/amazon-kinesis-client-net is over a year old, is there any plan on that regards?

**Comment by pfifer** [comment]
Thanks for the feedback and the PR.  We want to get all of the MultiLanguageDaemon clients up to date with the latest release of the Kinesis Client.  We should be able to add the approximateArrivalTimestamp as part of the updates.  

The PR looks pretty straight forward, and I will look into merging it.  This will also require updating the other clients to expose the property as well.

**Comment by zdjohn** [comment]
@pfifer awesome thanks!

**Comment by pfifer** [comment]
I've merged the PR.  I'm looking into adding support for the other languages, but I don't have a timeline on that right now.

**Comment by pfifer** [comment]
Support for the field is now available, but there are steps required to update the clients.  Currently the Python client has been updated to use the new functionality, and we're investigating updating the remainder of the clients.

**Comment by pfifer** [comment]
I created a issue to track adding the new features to the .NET client.  I'm going to close this for now, please feel free to reopen if you have more questions.
