### ISSUE TITLE
Should worker.shutdown() return a future for client to wait for the finalShutdown to be completed for worker to coordinate clean shutdown of system that uses the kinesis worker?

### ISSUE THREAD

**Issue by Jae** [awslabs/amazon-kinesis-client#87]
Hi I've came across a situation to wait for final shutodnw of kinesis worker to initiate orderly shutdown of the whole system that uses kinesis worker. I couldn't find a simple way to wait for the complete shutdown of kinesis worker. I might be missing the obvious.

If it's not possible, then would returning a future that you can wait on https://github.com/awslabs/amazon-kinesis-client/blob/master/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/Worker.java#L478 a good idea?

Regards
J

**Comment by pfifer** [comment]
I'm working on something similar for #79, that would return a future which finishes once all record processors have terminated.  This may not fulfill everything since some of the other threads could still be running e.g. the CloudWatch publishing thread.

**Comment by Jae** [comment]
oh cool thanks! I think that will probably cover most, as any shutdown cleanup would be related to the user supplied code that kinesis record processor runs.

**Comment by pfifer** [comment]
Release 1.7.1 added support for graceful shutdown.  Feel free to reopen this if you have more questions.
