### ISSUE TITLE
Strange behavior of KCL after AWS trouble in us-east-1

### ISSUE THREAD

**Issue by CyrilDevOps** [awslabs/amazon-kinesis-client#870]
We use KCL 2.3.1 in java,
yesterday (Dec 7 2021), AWS had lots of problem in us-east-1, lots of API call delay, dynamodb seems to have been impacted.

We saw in our log the leastlost method in the ShardRecordProcessor being call but there wasn't any initialize method called before.

It created problem in our code because some private variables weren't correctly initialized, we are going to hardened it for that problem.

Sadly we don't have much log of kcl/dynamodb lease manager.
But I think it is something that need to be investigated/documented.

Thanks

**Comment by zeynepsu** [comment]
Thank you for logging this issue. Please use the cloud support feature when facing with an issue like this, since we will require more information and logs from you to troubleshoot. Closing this issue.
