### ISSUE TITLE
Support `AT_TIMESTAMP`

### ISSUE THREAD

**Issue by Dinduks** [awslabs/amazon-kinesis-client#88]
Hi,

We want to specify a timestamp as a `InitialPositionInStream` so we can read from a specific point in time.
This feature is apparently currently unavailable and we'd like to add it to KCL.

It could look like this for example:
```java
clientLibConfiguration.withInitialPositionInStream(InitialPositionInStream.AT_TIMESTAMP)
    .withTimestamp(1234)
```

What do you think about this and what part of the code should I start looking into?

Thank you!

**Comment by pfifer** [comment]
I'm in the process of merging an internal change, and this should be coming soon.

**Comment by Dinduks** [comment]
Thanks @pfifer!
Any ETA for 1.7.0?
