### ISSUE TITLE
Is there a new 2.x.x release coming soon?

### ISSUE THREAD

**Issue by jzyeezy** [awslabs/amazon-kinesis-client#892]
I see that there were new `1.14.x` releases which include commits to address the log4j CVE. Will there be a release of the `2.x.x` of this library soon?

**Comment by zengyu714** [comment]
Yep, new [`v.2.3.10`](https://github.com/awslabs/amazon-kinesis-client/releases/tag/v2.3.10 ) is released this morning containing the upgrade of `logback` (the logging framework used in v2)

*Note*: maven central repository might take couple hours to update
