### ISSUE TITLE
Version 2.4.1 of amazon-kinesis-client-pom not published to maven central

### ISSUE THREAD

**Issue by FrelliBB** [awslabs/amazon-kinesis-client#933]
We had a dependabot update this morning to update from 2.4.0 to 2.4.1 but our CI fails because we are unable to find `amazon-kinesis-client-pom:2.4.1`.

```
[ERROR] Failed to execute goal on project ***: Could not resolve dependencies for project ***: Failed to collect dependencies at software.amazon.kinesis:amazon-kinesis-client:jar:2.4.1: Failed to read artifact descriptor for software.amazon.kinesis:amazon-kinesis-client:jar:2.4.1: Could not find artifact software.amazon.kinesis:amazon-kinesis-client-pom:pom:2.4.1
```

Manually checking maven central shows this is the case:

https://search.maven.org/artifact/software.amazon.kinesis/amazon-kinesis-client-pom
https://mvnrepository.com/artifact/software.amazon.kinesis/amazon-kinesis-client-pom

**Comment by zengyu714** [comment]
Checked that i didn't successfully release v2.4.1 for pom and multilang, will re-release shortly

**Comment by FrelliBB** [comment]
Thank you!

**Comment by zengyu714** [comment]
Just a heads up that the release may take up to 10 hours, i will check back
tomorrow to confirm the release, thank you!

**Comment by FrelliBB** [comment]
Looks like it was published correctly now, thank you @zengyu714!
