### ISSUE TITLE
shardConsumerDispatchPollIntervalMillis for MultiLangDaemon

### ISSUE THREAD

**Issue by richardwu** [awslabs/amazon-kinesis-client#950]
It doesn't seem like `CoordinatorConfig#shardConsumerDispatchPollIntervalMillis` is an option for MultiLangDaemon in the properties file, since `idleTimeBetweenReadsInMillis` was removed in v2.x: https://github.com/awslabs/amazon-kinesis-client/issues/515.

**Comment by akidambisrinivasan** [comment]
With the merged fix, for MultiLangDaemon in 2.x (once the latest release is out), please use the following in properties file to set the value for idleTimeBetweenReadsInMillis:

idleTimeBetweenReadsInMillis = 10000 # 10 seconds
