### ISSUE TITLE
Consuming DynamoDB Kinesis Streams and Binary datatypes with KCL does not decode base64 automatically

### ISSUE THREAD

**Issue by andklee** [awslabs/amazon-kinesis-client#959]
Not sure if this is an issue but I am noticing that when consuming a DynamoDB Kinesis Streams with items that are the Binary datatype, the value returned is the base64 encoded value of the Binary field and not the decoded value that the SDK would return with a get_item. I'm thinking that this is caused by serialization of the DynamoDB record when being put into Kinesis. 

Item stored in binary datatype:
```
byte[] arr = new byte[4];
arr[0] = 18;
arr[1] = 2;
arr[2] = 8;
arr[3] = 123;
```

Looks like the SDK encodes this to base64 when storing in DynamoDB:
```
"EgIIew=="
```

When getting the record from Kinesis, the value is encoded again:
```
"awsRegion":"us-east-1","eventID":"ad89cfbe-524e-4f20-bb70-275bf178961a","eventName":"MODIFY","userIdentity":null,"recordFormat":"application/json","tableName":"KSDSBinaryTesting","dynamodb":{"ApproximateCreationDateTime":1654699573622,"Keys":{"id":{"S":"1"}},"NewImage":{"id":{"S":"1"},"binaryData":{"B":"RWdJSWV3PT0="}},"OldImage":{"id":{"S":"1"},"binaryData":{"B":"RXdJSWV3PT0="}},"SizeBytes":37},"eventSource":"aws:dynamodb"}
```

Notice that the value for binaryData is RWdJSWV3PT0=. 

We need to decode RWdJSWV3PT0= to get EgIIew==

Code:
```
Base64.Decoder dec = Base64.getDecoder();
data = decoder.decode(record.getData()).toString();
software.amazon.awssdk.services.dynamodb.model.Record ddbRecord = objMapper.readValue(record.getData().array(), software.amazon.awssdk.services.dynamodb.model.Record.serializableBuilderClass()).build();
software.amazon.awssdk.services.dynamodb.model.StreamRecord streamRecord = ddbRecord.dynamodb();
ByteBuffer newBytesBuffer = streamRecord.newImage().get("binaryData").b().asByteBuffer();

byte[] newByteArray = dec.decode(newBytesString);
[LOG.info](http://log.info/)(newByteArray[0] + " " + newByteArray[1] + " " + newByteArray[2] + " " + newByteArray[3]);
```

Output:
```
[java] INFO: 18 2 8 123
```

Should I always decode Base64 for any Binary item?

**Comment by joshua-kim** [comment]
See the docs on [Record](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_Record.html). In short, the blob is always encoded in base64, so you'll need to deserialize in order to reconstruct the original object.
