### ISSUE TITLE
Confusing way of setting idleTimeBetweenReadsInMillis in PollingConfig

### ISSUE THREAD

**Issue by harodani** [awslabs/amazon-kinesis-client#999]
I was trying to set idleTimeBetweenReadsInMillis to increase the time between polls. PollingConfig has fluent setters via Lombok, meaning there is a method

`PollingConfig idleTimeBetweenReadsInMillis(long value)`

However this value is ignored because there is another method in the class 

`public void setIdleTimeBetweenReadsInMillis(long idleTimeBetweenReadsInMillis)`

This one does the same but also changes the value of a class boolean field called `usePollingConfigIdleTimeValue`. That it used afterwards in `retrievalFactory`

I think is very confusing having this two methods and one of them does not provide the desire functionality. 

Thanks!

**Comment by akidambisrinivasan** [comment]
Merged fix should address the issue. The `setIdleTimeBetweenReadsInMillis` API has been deprecated in favor of the fluent API which ensures the value is correctly configured
